/**
 * Markdown rendering of kitCatalog() for docs/kit-catalog.md (`pnpm kit:catalog`): one section
 * per prop (thumbnail, description, params table, anchors, methods), then environments,
 * effects, the character pack (kit.cast), one section per other available look and the
 * kit.voxel functions. Pure: the thumbnails are rendered by the generator.
 */
import type { KitCatalog } from './kit.js';
import type { KitCatalogEntry } from './registry.js';

export interface CatalogMarkdownOptions {
  /** Prop name -> thumbnail path relative to the markdown file. */
  readonly thumbnails?: Readonly<Record<string, string>> | undefined;
}

type Schema = Readonly<Record<string, unknown>>;

function asSchema(value: unknown): Schema {
  return typeof value === 'object' && value !== null ? (value as Schema) : {};
}

function cell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

/** Short type of a JSON Schema: 'a' | 'b', number, string[], [number, number], ... */
export function schemaType(input: unknown): string {
  const schema = asSchema(input);
  const choices = schema['enum'];
  if (Array.isArray(choices)) return choices.map((choice) => JSON.stringify(choice)).join(' | ');
  const union = schema['anyOf'] ?? schema['oneOf'];
  if (Array.isArray(union)) return union.map(schemaType).join(' | ');
  const tuple = schema['prefixItems'];
  if (Array.isArray(tuple)) return `[${tuple.map(schemaType).join(', ')}]`;
  const type = schema['type'];
  if (type === 'array') return `${schemaType(schema['items'])}[]`;
  if (type === 'integer') return 'integer';
  if (typeof type === 'string') return type;
  return 'function | value';
}

function range(schema: Schema): string {
  const min = schema['minimum'];
  const max = schema['maximum'];
  // z.int() emits the safe-integer limits: not worth printing.
  const shown = (value: unknown): value is number =>
    typeof value === 'number' && Math.abs(value) < Number.MAX_SAFE_INTEGER;
  if (shown(min) && shown(max)) return ` (${String(min)}..${String(max)})`;
  return '';
}

function paramsTable(entry: KitCatalogEntry): string[] {
  const properties = Object.entries(asSchema(entry.params['properties']));
  if (properties.length === 0) return ['No params.'];
  const rows = properties.map(([name, value]) => {
    const schema = asSchema(value);
    const fallback = 'default' in schema ? `\`${JSON.stringify(schema['default'])}\`` : '';
    const description = typeof schema['description'] === 'string' ? schema['description'] : '';
    return `| \`${name}\` | ${cell(schemaType(schema) + range(schema))} | ${cell(fallback)} | ${cell(description)} |`;
  });
  return ['| Param | Type | Default | Description |', '| --- | --- | --- | --- |', ...rows];
}

function list(title: string, items: Readonly<Record<string, string>>): string[] {
  const entries = Object.entries(items);
  if (entries.length === 0) return [];
  return ['', `${title}:`, '', ...entries.map(([name, text]) => `- \`${name}\`: ${text}`)];
}

function entrySection(namespace: string, entry: KitCatalogEntry, thumbnail?: string): string[] {
  return [
    `### \`kit.${namespace}.${entry.name}(params)\``,
    '',
    ...(thumbnail === undefined ? [] : [`![${entry.name}](${thumbnail})`, '']),
    entry.description,
    '',
    ...paramsTable(entry),
    ...list('Anchors (besides center, top, bottom, front, back, left, right)', entry.anchors),
    ...list('Methods', entry.methods ?? {}),
    '',
  ];
}

const VOXEL_LOOK = 'voxel';

function inLook(entries: readonly KitCatalogEntry[], look: string): KitCatalogEntry[] {
  return entries.filter((entry) => (entry.look ?? VOXEL_LOOK) === look);
}

/**
 * One section per available look other than voxel (ADR-009): its props, environments and
 * effects. Empty when only voxel is available, so the voxel catalog reads as before looks.
 */
function lookSections(catalog: KitCatalog, thumbnails: Readonly<Record<string, string>>): string[] {
  return catalog.looks
    .filter((look) => look.id !== VOXEL_LOOK)
    .flatMap((look) => [
      `## Look \`${look.id}\`: ${look.label}`,
      '',
      `${look.description}.`,
      '',
      ...inLook(catalog.props, look.id).flatMap((entry) =>
        entrySection('props', entry, thumbnails[entry.name]),
      ),
      ...inLook(catalog.env, look.id).flatMap((entry) => entrySection('env', entry)),
      ...inLook(catalog.fx, look.id).flatMap((entry) => entrySection('fx', entry)),
    ]);
}

export function kitCatalogMarkdown(
  catalog: KitCatalog,
  options: CatalogMarkdownOptions = {},
): string {
  const thumbnails = options.thumbnails ?? {};
  const voxelProps = inLook(catalog.props, VOXEL_LOOK);
  const lines = [
    '# Kit catalog',
    '',
    `Generated by \`pnpm kit:catalog\` from \`kitCatalog()\` (kit ${catalog.version}); do not edit by hand.`,
    'Scenes call `ctx.kit.<namespace>.<name>(params)` in `build()`; every result is a kit object',
    '(`.on(surface)`, `.mount(child, anchor)`, `.anchor(name)`). Animated objects have `update(t)`:',
    "call it from the scene's `update(t)` on every frame, like every other hook (pure functions of t).",
    'Props a video needs that the kit lacks are built per project as `kit-ext/props/<name>.js`',
    '(project-local, ADR-007); they are not listed here: `reelforge kit-docs` shows them.',
    '',
    '## Props',
    '',
    ...voxelProps.flatMap((entry) => entrySection('props', entry, thumbnails[entry.name])),
    '## Environments',
    '',
    ...inLook(catalog.env, VOXEL_LOOK).flatMap((entry) => entrySection('env', entry)),
    '## Effects',
    '',
    ...inLook(catalog.fx, VOXEL_LOOK).flatMap((entry) => entrySection('fx', entry)),
    '## Characters (`kit.cast`)',
    '',
    'The character pack (ADR-024, docs/characters.md): scenes call the positional forms',
    "`kit.cast.mascot('bulb', params)`, `kit.cast.person('engineer', params)`, `kit.cast.mannequin(params)`,",
    '`kit.cast.role(spec, params)`; the params below include the id / spec. Details and the role-spec',
    'vocabulary: `reelforge kit-docs characters`.',
    '',
    ...catalog.cast.flatMap((entry) => entrySection('cast', entry, thumbnails[entry.name])),
    ...lookSections(catalog, thumbnails),
    '## Voxel toolbox (`kit.voxel`)',
    '',
    '| Function | Description |',
    '| --- | --- |',
    ...Object.values(catalog.voxel).map(
      (doc) => `| \`${cell(doc.signature)}\` | ${cell(doc.description)} |`,
    ),
    '',
  ];
  return lines.join('\n');
}
