/**
 * Markdown rendering of kitCatalog() for docs/kit-catalog.md (`pnpm kit:catalog`): one section
 * per prop (thumbnail, description, params table, anchors, methods), then environments,
 * effects and the kit.voxel functions. Pure: the thumbnails are rendered by the generator.
 */
import type { KitCatalog } from './kit.js';
import type { KitCatalogEntry } from './registry.js';

export interface CatalogMarkdownOptions {
  /** Prop name -> thumbnail path relative to the markdown file. */
  readonly thumbnails?: Readonly<Record<string, string>> | undefined;
}

type Schema = Readonly<Record<string, unknown>>;

function asSchema(value: unknown): Schema {
  return typeof value === 'object' && value !== null ? (value as Schema) : {};
}

function cell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

/** Short type of a JSON Schema: 'a' | 'b', number, string[], [number, number], ... */
export function schemaType(input: unknown): string {
  const schema = asSchema(input);
  const choices = schema['enum'];
  if (Array.isArray(choices)) return choices.map((choice) => JSON.stringify(choice)).join(' | ');
  const union = schema['anyOf'] ?? schema['oneOf'];
  if (Array.isArray(union)) return union.map(schemaType).join(' | ');
  const tuple = schema['prefixItems'];
  if (Array.isArray(tuple)) return `[${tuple.map(schemaType).join(', ')}]`;
  const type = schema['type'];
  if (type === 'array') return `${schemaType(schema['items'])}[]`;
  if (type === 'integer') return 'integer';
  if (typeof type === 'string') return type;
  return 'function | value';
}

function range(schema: Schema): string {
  const min = schema['minimum'];
  const max = schema['maximum'];
  // z.int() emits the safe-integer limits: not worth printing.
  const shown = (value: unknown): value is number =>
    typeof value === 'number' && Math.abs(value) < Number.MAX_SAFE_INTEGER;
  if (shown(min) && shown(max)) return ` (${String(min)}..${String(max)})`;
  return '';
}

function paramsTable(entry: KitCatalogEntry): string[] {
  const properties = Object.entries(asSchema(entry.params['properties']));
  if (properties.length === 0) return ['No params.'];
  const rows = properties.map(([name, value]) => {
    const schema = asSchema(value);
    const fallback = 'default' in schema ? `\`${JSON.stringify(schema['default'])}\`` : '';
    const description = typeof schema['description'] === 'string' ? schema['description'] : '';
    return `| \`${name}\` | ${cell(schemaType(schema) + range(schema))} | ${cell(fallback)} | ${cell(description)} |`;
  });
  return ['| Param | Type | Default | Description |', '| --- | --- | --- | --- |', ...rows];
}

function list(title: string, items: Readonly<Record<string, string>>): string[] {
  const entries = Object.entries(items);
  if (entries.length === 0) return [];
  return ['', `${title}:`, '', ...entries.map(([name, text]) => `- \`${name}\`: ${text}`)];
}

function entrySection(namespace: string, entry: KitCatalogEntry, thumbnail?: string): string[] {
  return [
    `### \`kit.${namespace}.${entry.name}(params)\``,
    '',
    ...(thumbnail === undefined ? [] : [`![${entry.name}](${thumbnail})`, '']),
    entry.description,
    '',
    ...paramsTable(entry),
    ...list('Anchors (besides center, top, bottom, front, back, left, right)', entry.anchors),
    ...list('Methods', entry.methods ?? {}),
    '',
  ];
}

export function kitCatalogMarkdown(
  catalog: KitCatalog,
  options: CatalogMarkdownOptions = {},
): string {
  const thumbnails = options.thumbnails ?? {};
  const lines = [
    '# Kit catalog',
    '',
    `Generated by \`pnpm kit:catalog\` from \`kitCatalog()\` (kit ${catalog.version}); do not edit by hand.`,
    'Scenes call `ctx.kit.<namespace>.<name>(params)` in `build()`; every result is a kit object',
    '(`.on(surface)`, `.mount(child, anchor)`, `.anchor(name)`). Animated objects have `update(t)`:',
    "call it from the scene's `update(t)` on every frame, like every other hook (pure functions of t).",
    '',
    '## Props',
    '',
    ...catalog.props.flatMap((entry) => entrySection('props', entry, thumbnails[entry.name])),
    '## Environments',
    '',
    ...catalog.env.flatMap((entry) => entrySection('env', entry)),
    '## Effects',
    '',
    ...catalog.fx.flatMap((entry) => entrySection('fx', entry)),
    '## Voxel toolbox (`kit.voxel`)',
    '',
    '| Function | Description |',
    '| --- | --- |',
    ...Object.values(catalog.voxel).map(
      (doc) => `| \`${cell(doc.signature)}\` | ${cell(doc.description)} |`,
    ),
    '',
  ];
  return lines.join('\n');
}
