/**
 * `reelforge kit-docs characters` (also `cast`, `kit.cast`, `cast.<name>` and the four factory
 * names): the character pack reference (ADR-024), generated by the kit. The index lists the
 * pack in one line pointing here, so it stays inside its size budget.
 */
import { charactersDocs } from '@reelforge/kit';

export const CHARACTERS_TOPIC = 'characters';

const ALIASES = new Set(['characters', 'cast', 'mascot', 'person', 'mannequin', 'role']);

/** One index line for the pack. */
export const CHARACTERS_INDEX_LINE =
  'kit.cast (characters: mascots bulb/screen/fox/bean, 10 cast members, mannequin, role specs for new professions; poses, expressions, walkTo, lookAt): reelforge kit-docs characters';

/** The pack reference when `name` (without `kit.`) names it, else undefined. */
export function describeCharacters(name: string): string | undefined {
  const [first, second] = name.split('.');
  if (first === 'cast' && second !== undefined) return charactersDocs();
  return second === undefined && first !== undefined && ALIASES.has(first)
    ? charactersDocs()
    : undefined;
}
