/**
 * `reelforge kit-docs characters` (also `cast`, `kit.cast`, `cast.<name>`, the four factory names
 * and the id of a mascot, a cast member or a project role): the character pack reference
 * (ADR-024), generated by the kit. The index lists the pack in one line pointing here, so it stays
 * inside its size budget.
 */
import { CAST, charactersDocs, MASCOTS, type ProjectCast } from '@reelforge/kit';

export const CHARACTERS_TOPIC = 'characters';

const ALIASES = new Set(['characters', 'cast', 'mascot', 'person', 'mannequin', 'role']);

/** One index line for the pack. */
export const CHARACTERS_INDEX_LINE =
  'kit.cast (characters: mascots bulb/screen/fox/bean, 10 cast members, mannequin, role specs for new professions; poses, expressions, walkTo, lookAt): reelforge kit-docs characters';

/** How a scene calls the character `id` names (a mascot, a cast member or a project role). */
function characterCall(id: string, cast: ProjectCast | undefined): string | undefined {
  if ((MASCOTS as readonly string[]).includes(id)) {
    return `${id} is a mascot: ctx.kit.cast.mascot('${id}')`;
  }
  if ((CAST as readonly string[]).includes(id)) {
    return `${id} is a cast member: ctx.kit.cast.person('${id}')`;
  }
  if (cast?.roles.has(id) === true) {
    return `${id} is a role of this project (characters/roles/${id}.json): ctx.kit.cast.person('${id}')`;
  }
  return undefined;
}

/**
 * The pack reference (with the project's roles and accessories, ADR-026) when `name` (without
 * `kit.`) names it or one of its characters, else undefined.
 */
export function describeCharacters(name: string, cast?: ProjectCast): string | undefined {
  const [first, second] = name.split('.');
  if (first === 'cast' && second !== undefined) return charactersDocs(cast);
  if (second !== undefined || first === undefined) return undefined;
  if (ALIASES.has(first)) return charactersDocs(cast);
  const call = characterCall(first, cast);
  return call === undefined ? undefined : `${call}; the pack reference:\n${charactersDocs(cast)}`;
}
