// Bundles prompts/*.md into src/generated/prompt-sources.ts (string constants + sha256), so the
// library never reads prompt files at runtime (Electron main, packaged app, Node tests alike).
// Run after editing a prompt: pnpm --filter @reelforge/prompts generate
// The unit tests fail when the generated module is stale.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';

const packageDir = path.join(import.meta.dirname, '..');
const promptsDir = path.join(packageDir, 'prompts');
const outFile = path.join(packageDir, 'src', 'generated', 'prompt-sources.ts');

const files = readdirSync(promptsDir)
  .filter((name) => name.endsWith('.md'))
  .sort();

const entries = files.map((name) => {
  const source = readFileSync(path.join(promptsDir, name), 'utf8').replaceAll('\r\n', '\n');
  const sha256 = createHash('sha256').update(source, 'utf8').digest('hex');
  return { id: name.slice(0, -'.md'.length), source, sha256 };
});

const body = [
  '// GENERATED by scripts/generate-prompts.mjs from prompts/*.md. Do not edit by hand.',
  '',
  `export const PROMPT_IDS = ${JSON.stringify(entries.map((entry) => entry.id))} as const;`,
  'export type PromptId = (typeof PROMPT_IDS)[number];',
  '',
  'export interface PromptSource {',
  '  /** File content (front matter + template), LF line endings. */',
  '  readonly source: string;',
  '  readonly sha256: string;',
  '}',
  '',
  'export const PROMPT_SOURCES: Readonly<Record<PromptId, PromptSource>> = {',
  ...entries.map(
    (entry) =>
      `  ${JSON.stringify(entry.id)}: { source: ${JSON.stringify(entry.source)}, sha256: ${JSON.stringify(entry.sha256)} },`,
  ),
  '};',
  '',
].join('\n');

const options = (await prettier.resolveConfig(outFile)) ?? {};
const formatted = await prettier.format(body, { ...options, filepath: outFile });
writeFileSync(outFile, formatted, 'utf8');
process.stdout.write(
  `wrote ${path.relative(packageDir, outFile)} (${String(entries.length)} prompts)\n`,
);
