/**
 * The ten side-cast members of the concept page as role specs (ADR-024): presets of the same
 * builder every new profession uses (`kit.cast.role(spec)`), plus two example roles built only
 * from the vocabulary (firefighter, chef). Colours are the page's.
 */
import type { RoleSpecInput } from './role-spec.js';

export const CAST = [
  'scientist',
  'doctor',
  'engineer',
  'finance',
  'teacher',
  'historian',
  'kid',
  'hacker',
  'detective',
  'astronaut',
] as const;

export type CastId = (typeof CAST)[number];

export const CAST_SPECS: Readonly<Record<CastId, RoleSpecInput>> = {
  scientist: {
    id: 'scientist',
    label: 'Scientist',
    description: 'knee-length lab coat, wild grey hair, goggles on the forehead, glowing flask',
    hair: { style: 'messy', color: 'slateGrey' },
    top: { color: 'brightTeal' },
    layers: [{ id: 'labCoat', color: 'cream' }],
    legs: { color: 'darkSlate' },
    shoes: { color: 'darkSlate' },
    accessories: ['goggles'],
    held: 'flask',
  },
  doctor: {
    id: 'doctor',
    label: 'Doctor',
    description: 'one-colour scrubs, scrub cap, mask, stethoscope, clipboard',
    skin: 'tan',
    hair: { style: 'none' },
    headgear: { id: 'scrubCap', color: 'teal' },
    top: { color: 'teal' },
    legs: { color: 'teal' },
    shoes: { color: 'cream' },
    accessories: ['mask', 'stethoscope', 'badge'],
    held: 'clipboard',
  },
  engineer: {
    id: 'engineer',
    label: 'Engineer',
    description: 'hard hat, hi-vis vest with stripes, boots, big wrench',
    skin: 'brown',
    hair: { style: 'cropped', color: 'darkSlate' },
    headgear: { id: 'hardHat', color: 'lightOrange' },
    top: { color: 'slateBlue' },
    layers: [{ id: 'hiVis', color: 'green' }],
    legs: { color: 'slateBlue' },
    shoes: { style: 'boots', color: 'darkSlate' },
    held: 'wrench',
  },
  finance: {
    id: 'finance',
    label: 'Finance',
    description: 'tall in a narrow suit, pink tie, glasses, briefcase',
    body: 'tall',
    skin: 'tan',
    hair: { style: 'slick', color: 'indigo' },
    top: { color: 'darkSlate' },
    layers: [
      { id: 'suit', color: 'midSlate' },
      { id: 'tie', color: 'pink' },
    ],
    legs: { color: 'darkSlate' },
    shoes: { color: 'rust' },
    accessories: ['glassesSquare'],
    held: 'briefcase',
  },
  teacher: {
    id: 'teacher',
    label: 'Teacher',
    description: 'hair in a bun, round glasses, sweater and skirt, pointer',
    hair: { style: 'bun', color: 'burntOrange' },
    top: { color: 'wine' },
    layers: ['vNeck', { id: 'skirt', color: 'slateBlue' }],
    legs: { color: 'darkSlate' },
    shoes: { color: 'rust' },
    accessories: ['glassesRound'],
    held: 'pointer',
  },
  historian: {
    id: 'historian',
    label: 'Historian',
    description: 'big white beard, bald top, tweed jacket with elbow patches, scroll',
    body: 'broad',
    hair: { style: 'bald', color: 'cream' },
    top: { color: 'tan' },
    layers: [{ id: 'tweed', color: 'tan', trim: 'rust' }],
    legs: { color: 'rust' },
    shoes: { color: 'darkSlate' },
    accessories: ['beard'],
    held: 'scroll',
  },
  kid: {
    id: 'kid',
    label: 'Kid',
    description: 'smaller, huge backpack, cap backwards, shorts',
    body: 'kid',
    skin: 'tan',
    hair: { style: 'fringe', color: 'indigo' },
    headgear: { id: 'capBack', color: 'brightTeal' },
    top: { color: 'lightOrange' },
    legs: { style: 'shorts', color: 'slateBlue' },
    shoes: { color: 'pink' },
    accessories: [{ id: 'backpack', color: 'pink' }],
  },
  hacker: {
    id: 'hacker',
    label: 'Hacker',
    description: 'oversized pointed hood, face in shadow with glowing eyes, tablet',
    body: 'broad',
    hair: { style: 'none' },
    headgear: { id: 'hood', color: 'darkSlate' },
    top: { color: 'darkSlate' },
    layers: [{ id: 'hoodie', color: 'darkSlate', trim: 'midSlate', detail: 'green' }],
    legs: { color: 'midSlate' },
    shoes: { color: 'brightTeal' },
    eyes: { style: 'glow', color: 'green' },
    held: 'tablet',
  },
  detective: {
    id: 'detective',
    label: 'Detective',
    description: 'trench coat with a raised collar, wide-brimmed hat, magnifier',
    hair: { style: 'neckline', color: 'darkSlate' },
    headgear: { id: 'fedora', color: 'darkSlate', trim: 'rust' },
    top: { color: 'tan' },
    layers: [{ id: 'trenchCoat', color: 'tan', trim: 'rust', detail: 'burntOrange' }],
    legs: { color: 'darkSlate' },
    shoes: { color: 'rust' },
    held: 'magnifier',
  },
  astronaut: {
    id: 'astronaut',
    label: 'Astronaut',
    description: 'bubble helmet with a visor, bulky suit, life-support pack',
    body: 'bulky',
    hair: { style: 'none' },
    headgear: { id: 'spaceHelmet', color: 'cream', trim: 'teal' },
    top: { color: 'cream' },
    layers: [{ id: 'spaceSuit', trim: 'slateGrey', detail: 'orange' }],
    legs: { color: 'cream' },
    shoes: { style: 'boots', color: 'slateGrey' },
    accessories: ['lifePack'],
  },
};

/** Example roles from the vocabulary only (docs/characters.md, render goldens). */
export const EXAMPLE_ROLES: readonly RoleSpecInput[] = [
  {
    id: 'firefighter',
    label: 'Firefighter',
    description: 'helmet with a shield, turnout coat with reflective bands, air tank, axe',
    skin: 'tan',
    hair: { style: 'cropped', color: 'darkSlate' },
    headgear: { id: 'fireHelmet', color: 'burntOrange', trim: 'lightOrange' },
    top: { color: 'tan' },
    layers: [{ id: 'turnoutCoat', color: 'tan', trim: 'green' }],
    legs: { color: 'tan' },
    shoes: { style: 'boots', color: 'black' },
    accessories: ['airTank'],
    held: 'axe',
  },
  {
    id: 'chef',
    label: 'Chef',
    description: "toque, double-breasted chef's jacket, neckerchief, spatula",
    skin: 'tan',
    hair: { style: 'short', color: 'indigo' },
    headgear: 'chefHat',
    top: { color: 'cream' },
    layers: ['chefJacket'],
    legs: { color: 'darkSlate' },
    shoes: { color: 'black' },
    accessories: [{ id: 'neckerchief', color: 'pink' }],
    held: 'spatula',
  },
];
