/**
 * Contact sheets of the Grim Ink project modules (PLAN.md#14.8): a generated standalone scene that
 * paints one sheet page per second on the world's ink stage (`kit.people.<id>.sheet(g, page)` /
 * `kit.places.<id>.sheet(g, page)`), rendered like any scene (preview = export = module preview),
 * then the pages composed into one labelled PNG, and the code checks (pages not blank, the first
 * page identical when rendered again).
 */
import { computeFrameStats, type RgbaImage } from '@reelforge/engine/raster';
import { PERSON_SHEET_PAGES, PLACE_SHEET_PAGES } from '@reelforge/kit';
import { kitExtensionFile } from '@reelforge/shared';
import { blankFrameNote } from '../render/blank.js';
import { composeSheet, type SheetRow } from '../render/sheet.js';

export type InkPreviewKind = 'people' | 'places';

/** Standalone shot id of the sheet scene. */
export const INK_SHEET_SHOT_ID = 'ink-sheet';

interface KindText {
  readonly noun: string;
  readonly pages: number;
  readonly labels: readonly string[];
}

const KINDS: Readonly<Record<InkPreviewKind, KindText>> = {
  people: {
    noun: 'person',
    pages: PERSON_SHEET_PAGES,
    labels: [
      '6 views (front, 3/4, profile, back, profile L, 3/4 L) x stand / akimbo / walk',
      '14 faces: deadpan miserable exhausted shock rage smug scared / confused sad yelling disgust grin asleep focused',
    ],
  },
  places: {
    noun: 'place',
    pages: PLACE_SHEET_PAGES,
    labels: ['wide (all of it)', 'medium (x2 on the light)', 'close (x3.2 on the first anchor)'],
  },
};

export function inkPreviewNoun(kind: InkPreviewKind): string {
  return KINDS[kind].noun;
}

/** Project-relative files of a module's preview (git-ignored app data). */
export function inkPreviewPaths(
  kind: InkPreviewKind,
  id: string,
): { scene: string; sheet: string; dir: string } {
  const dir = `.reelforge/frames/${kind}/${id}`;
  return { dir, scene: `${dir}/sheet.js`, sheet: `${dir}/sheet.png` };
}

/** Local times rendered: page i at i + 0.5 s, then page 0 again (determinism check). */
export function inkSheetTimes(kind: InkPreviewKind): number[] {
  const pages = KINDS[kind].pages;
  return [...Array.from({ length: pages }, (_, index) => index + 0.5), pages + 0.5];
}

/** Length of the standalone sheet shot (s). */
export function inkSheetDuration(kind: InkPreviewKind): number {
  return KINDS[kind].pages + 1;
}

/** The scene module (lint-clean, deterministic) that shows the sheet pages of `kit.<kind>.<id>`. */
export function inkSheetSource(kind: InkPreviewKind, id: string): string {
  const { noun, pages } = KINDS[kind];
  return `// Generated by reelforge ${kind}-preview: the contact sheet of kit.${kind}.${id}, one page per second.
export const meta = { id: '${INK_SHEET_SHOT_ID}', title: 'Grim Ink ${noun} ${id}', treatment: 'metaphor-object' };

const ID = ${JSON.stringify(id)};
const PAGES = ${String(pages)};

export function build(ctx) {
  const registry = ctx.kit.${kind};
  if (registry === undefined) {
    throw new Error('kit.${kind} exists only in the Grim Ink (c-cam) style');
  }
  const item = registry[ID];
  const stage = ctx.kit.fx.inkStage();
  ctx.scene.add(stage);
  return { stage, item };
}

export function update(t, s) {
  const page = Math.floor(t) % PAGES;
  s.stage.paint(t, (g) => s.item.sheet(g, page));
}
`;
}

export interface InkSheetFrame {
  /** Local shot time. */
  readonly t: number;
  readonly image: RgbaImage;
}

function frameAt(frames: readonly InkSheetFrame[], t: number): InkSheetFrame | undefined {
  return frames.find((frame) => Math.abs(frame.t - t) < 1e-6);
}

/** The pages, 2 per row at half size, labelled (for Claude and the critic). */
export function inkSheet(
  kind: InkPreviewKind,
  id: string,
  frames: readonly InkSheetFrame[],
  size: { readonly width: number; readonly height: number },
): RgbaImage {
  const { noun, labels } = KINDS[kind];
  const tiles = labels.map((label, index) => {
    const frame = frameAt(frames, index + 0.5);
    return frame ? { label, frame: frame.image } : { label, failure: 'NOT RENDERED' };
  });
  const rows: SheetRow[] = [];
  for (let index = 0; index < tiles.length; index += 2) {
    rows.push({ tiles: tiles.slice(index, index + 2) });
  }
  return composeSheet(
    {
      title: `${noun} ${id} - contact sheet (${kitExtensionFile(kind, id)})`,
      frameWidth: size.width,
      frameHeight: size.height,
      factor: 2,
    },
    rows,
  );
}

export interface InkCheck {
  readonly id: 'blank' | 'deterministic';
  readonly ok: boolean;
  readonly message: string;
}

function sameBytes(first: Uint8Array, second: Uint8Array): boolean {
  const view = (bytes: Uint8Array): Buffer =>
    Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  return view(first).equals(view(second));
}

/** Checks by code: every page drawn (not blank) and page 0 identical when rendered again. */
export function inkSheetChecks(kind: InkPreviewKind, frames: readonly InkSheetFrame[]): InkCheck[] {
  const { pages, labels } = KINDS[kind];
  const blank = labels.flatMap((label, index) => {
    const frame = frameAt(frames, index + 0.5);
    const note =
      frame === undefined ? 'not rendered' : blankFrameNote(computeFrameStats(frame.image.data));
    return note === undefined ? [] : [`page ${String(index + 1)} (${label}): ${note}`];
  });
  const first = frameAt(frames, 0.5);
  const repeat = frameAt(frames, pages + 0.5);
  const deterministic =
    first !== undefined && repeat !== undefined && sameBytes(first.image.data, repeat.image.data);
  return [
    blank.length === 0
      ? { id: 'blank', ok: true, message: `${String(pages)} pages rendered, none blank` }
      : { id: 'blank', ok: false, message: blank.join('; ') },
    deterministic
      ? { id: 'deterministic', ok: true, message: 'the first page rendered twice is identical' }
      : {
          id: 'deterministic',
          ok: false,
          message:
            'the first page differs when rendered again: a drawing keeps state between calls or uses randomness (use ink.time.rnd / hash with fixed seeds)',
        },
  ];
}
