/**
 * Lineup of a project role (PLAN.md#12.20, ADR-026): a generated standalone scene that shows the
 * role alone on a neutral stage, four angles in the calm pose and two poses, one view per second
 * (the last second repeats the first view: determinism), and reports the role's rest size and the
 * pack's height range as an sfx cue (`role-metrics {json}`, the value channel every render path
 * returns). Rendered like any scene, so preview = export = role QA.
 */
import type { RgbaImage } from '@reelforge/engine/raster';
import { CAST } from '@reelforge/kit';
import { composeSheet, type SheetRow } from '../render/sheet.js';

export interface LineupView {
  /** Turn of the role (degrees, 0 = facing the camera). */
  readonly angle: number;
  readonly pose: string;
}

/** Four angles calm, then two poses at a 3/4 view. */
export const LINEUP_VIEWS: readonly LineupView[] = [
  { angle: 0, pose: 'calm' },
  { angle: 90, pose: 'calm' },
  { angle: 180, pose: 'calm' },
  { angle: 270, pose: 'calm' },
  { angle: 25, pose: 'wave' },
  { angle: -25, pose: 'point' },
];

/** Cue name prefix of the measurements. */
export const ROLE_METRICS_CUE = 'role-metrics ';
/** Standalone shot id of the lineup scene (its file name). */
export const LINEUP_SHOT_ID = 'lineup';

/** Project-relative files of a role's preview (git-ignored app data). */
export function rolePreviewPaths(id: string): { scene: string; sheet: string; dir: string } {
  const dir = `.reelforge/frames/roles/${id}`;
  return { dir, scene: `${dir}/lineup.js`, sheet: `${dir}/lineup.png` };
}

/** Local times rendered: view i at i + 0.5 s, then view 0 again (determinism check). */
export function lineupTimes(views: readonly LineupView[] = LINEUP_VIEWS): number[] {
  return [...views.map((_, index) => index + 0.5), views.length + 0.5];
}

export function lineupDuration(views: readonly LineupView[] = LINEUP_VIEWS): number {
  return views.length + 1;
}

/** The scene module (lint-clean, deterministic) that shows `kit.cast.person(id)` in each view. */
export function lineupSource(id: string, views: readonly LineupView[] = LINEUP_VIEWS): string {
  return `// Generated by reelforge cast preview: the role ${id} alone, one view per second.
export const meta = { id: '${LINEUP_SHOT_ID}', title: 'Role ${id}', treatment: 'character-scene' };

const ROLE = ${JSON.stringify(id)};
const PACK = ${JSON.stringify(CAST)};
const VIEWS = ${JSON.stringify(views)};
// Every view shows the character at the same time of its own clock: views differ only by angle and pose.
const POSE_TIME = 1.2;

export function build(ctx) {
  const { kit, scene, three, palette, sfx } = ctx;
  scene.background = new three.Color(palette.sky);
  scene.add(kit.env.lights());
  const poses = [...new Set(VIEWS.map((view) => view.pose))];
  const people = poses.map((pose) => kit.cast.person(ROLE, { pose, seed: 1 }));
  const box = people[0].bounds();
  const size = [box.max.x - box.min.x, box.max.y - box.min.y, box.max.z - box.min.z];
  const heights = PACK.map((member) => kit.cast.person(member, { seed: 1 }).bounds().max.y);
  sfx.at(0, '${ROLE_METRICS_CUE}' + JSON.stringify({ size, packHeight: [Math.min(...heights), Math.max(...heights)] }));
  const pivot = kit.voxel.group();
  for (const person of people) pivot.add(person);
  const reach = Math.max(Math.hypot(size[0], size[2]), 0.5);
  const plate = kit.voxel.mesh(kit.voxel.box([16, 1, 16], 'groundAlt'), {
    voxelSize: (reach * 1.3) / 16,
    pivot: [8, 1, 8],
  });
  scene.add(plate, pivot);
  const h = size[1];
  const dist = Math.max(1.75 * h, 1.1 * reach, 1.4);
  return { pivot, people, poses, h, dist };
}

export function update(t, s, ctx) {
  const view = VIEWS[Math.min(Math.floor(t), VIEWS.length) % VIEWS.length];
  s.pivot.rotation.y = (view.angle * Math.PI) / 180;
  s.people.forEach((person, index) => {
    person.visible = s.poses[index] === view.pose;
    person.update(POSE_TIME);
  });
  ctx.camera.set({ position: [0, s.h * 0.6 + s.dist * 0.25, s.dist], target: [0, s.h * 0.5, 0] });
}
`;
}

export interface LineupFrame {
  readonly t: number;
  readonly image: RgbaImage;
}

function viewLabel(id: string, view: LineupView): string {
  return view.pose === 'calm' ? `${id} ${String(view.angle)} deg` : `${id} ${view.pose}`;
}

/** 3 views per row, labelled, native pixels (for Claude and the critic). */
export function lineupSheet(
  id: string,
  frames: readonly LineupFrame[],
  size: { readonly width: number; readonly height: number },
  views: readonly LineupView[] = LINEUP_VIEWS,
): RgbaImage {
  const tiles = views.map((view, index) => {
    const frame = frames.find((candidate) => Math.abs(candidate.t - (index + 0.5)) < 1e-6);
    const label = viewLabel(id, view);
    return frame ? { label, frame: frame.image } : { label, failure: 'NOT RENDERED' };
  });
  const rows: SheetRow[] = [];
  for (let index = 0; index < tiles.length; index += 3) {
    rows.push({ tiles: tiles.slice(index, index + 3) });
  }
  return composeSheet(
    {
      title: `role ${id} - 4 angles + 2 poses (characters/roles/${id}.json)`,
      frameWidth: size.width,
      frameHeight: size.height,
      factor: 1,
    },
    rows,
  );
}
