/**
 * The documented methods of `kit.fx.b1Screen` (kit catalog, kit-docs). The showcase's pieces
 * (showcase.ts) are named only in the room() line.
 */
import { GAME_B1_SHOWCASE_LINE } from '../showcase.js';

export const SCREEN_METHODS = {
  'update(t)': 'Repaints the frame for local time t: call it every frame',
  'tv((g, t) => { ... })':
    "Paints the picture INSIDE the TV with Atari 2600 rules, in TV units (160 x 180, one unit = 4 x 2 px). g: rect(x, y, w, h, colour), dither(x, y, w, h, colour, level), bands(x, w, [[y, colour], ...], y1) colour per line, playfield(y, h, '20 bits', colour, { mirror }) 16-px blocks, sprite(rows, colour | [colour per row], x, y, { stretch, rowH, flip, squash, playfield, flicker }) <= 16 bits, ONE colour per row, text(str, x, y, { colour, size, type: { at, cps } }) Joy caps, score(str, x, y, { colour, cell: [w, h] }) 2600 score digits, remap('dim' | 'flash' | 'drain' | 'ghost' | 'cycle1' | 'cycle2' | 'cycle3', level, [y0, y1] rows), rectPx(x, y, w, h, colour) square px ONLY for a newer console's thing, attract(), garbage(seed), offset(dx, dy) px shake, util { seg, lerp, ease, hash, shake, typed, frameOf, path(keys [[t, x, y]], t, { ease, fps }) -> { x, y, dir, moving }, scroll(t, unitsPerSecond) -> blocks, hit(boxA, boxB) }, t, frame. The film's own vocabulary: draw(id, x, y, { frame, at (one-shot), phase, face, squash, flicker, playfield, colour, size }), field(id, y, { shift, colour, rows: [a, b] }), box(id, x, y), ball / missile(x, y, { w: 1 | 2 | 4 | 8, h, colour }), counter({ means, keys: [[t, value]], x, y, colour, cell }) only for a real number. More than 2 sprites on a scanline flicker on alternate frames (flicker: false = the hero; playfield: true = resting objects; NUSIZ copies count once)",
  'room({ calendar: { month, mark, markAt } | false, lamp })': `The plain living room around the TV (wood panelling, shag carpet, the TV with rabbit ears, the console and joystick); a wall calendar with a hand-ringed day only when given (default none), a table lamp. The film's own room: interior(). ${GAME_B1_SHOWCASE_LINE}`,
  "camera([{ at, on: 'room' | 'tv' | 'calendar' | 'console' | x, y, zoom, ease }])":
    "Room camera keys; 'tv' = inside the TV (its picture fills the frame): a push from 'room' to 'tv' grows the picture out of the glass, 'tv' -> 'room' pulls back. Without room() the frame is the TV picture",
  'year(text, { at })':
    'The HUD year: call again to roll to a new year (odometer, the old one burns in)',
  'score({ label, keys: [[t, value]], at, until })':
    'A number from the story counting on the HUD (pops and flashes gold on change)',
  'progress({ from, to, slots })':
    'Film progress as slots on the HUD (slots = shots, from / to = this shot`s share of the film)',
  'checkpoint({ label, at, until })': 'Chapter: a flag pops over the current slot, its name types',
  'lives({ label, max, keys: [[t, n]], at, until })':
    'Hearts: ONLY for the one thing really under threat; a lost one blinks then goes hollow',
  "boss({ num, name, from: 'left' | 'right' | 'top', x, y, at, hp: { n, label, keys: [[t, value]] }, defeat })":
    'Boss card for the central problem (in-game, gets the CRT): BOSS n types, the name slams in with overshoot and shake, HP segments arrive unevenly; each lost segment flashes and shakes; defeat = flicker death',
  "say(text, { speaker, at, until, place: 'bottom' | 'top' }) / narrate(text, { at, until })":
    'Dialogue box (CAPS, \\n, <= 3 lines) typed at an irregular voiced cadence, a blinking cursor; returns { at, end }',
  "note(['WEAK POINT:', 'MORE TIME'], { at, x, y, w, h, angle, under, strike: { line, at }, tick })":
    'A sticky note slapped on the TV glass in a hurried hand (picture px): underlined twice, struck out in crimson or ticked',
  "defineSprite(id, { rows | frames, colours, size: 1 | 2 | 4, copies: 1-3, gap: 'close' | 'medium' | 'wide', rowH, fps, faces, describe })":
    "The film's OWN TV things (the world is a style grammar, not the showcase's catalogue): a 2600 player of <= 8 bits ('#' / '.') per row, ONE colour per row (an ink, a list, or row stops { 0: 'tan', 3: 'teal' }), stretched OR copied (NUSIZ); violations come back as sentences. Returns { w, h, frames } in TV units",
  "definePlayfield(id, { rows: ['20 or 40 bits'], rowH, colours, mode: 'mirror' | 'repeat' })":
    'Scenery as playfield: 20-bit rows (mirrored or repeated) or 40-bit asymmetric rows of 4-unit blocks, one colour per row',
  "generate(id, { kind: 'tree' | 'bush' | 'cactus' | 'seaweed' | 'rock' | 'bird' | 'fish' | 'animal' | 'insect' | 'reptile' | 'person' | 'vehicle' | 'building' | 'item' | 'boss' | 'effect' | 'scenery', ...traits, seed, size, copies })":
    'Seeded generators in the 2600 grammar: trees (pine, round, palm, birch, dead), animals (like: deer, horse, camel, dog, cow, bear, goat; or neck, legs, horns, hump, tail), people (role: ranger, miner, sailor, knight, astronaut, clerk, farmer, kid; hat, tool, colours), vehicles, buildings, items, a boss from traits (body: blob, cloud, wave, clock, swarm, tower, beast; eyes, mouth, arms, crown), effects (explosion, splash, smoke, sparkle, dust), scenery playfields (canopy, waves, dunes, hills, skyline, wall, reef, clouds, ground)',
  "assets({ version: 1, world: 'game-b1', sprites, playfields, generated, rooms })":
    "Loads one project asset file (assets/game-b1/<name>.json: the film's own vocabulary) into this screen; every problem names the file and the id",
  'interior({ shell, wall, floor, light, calendar: { month, year, mark, markAt } | false, props: [...], defaults, carts } | roomId)':
    "The room around the TV is the film's own: shells living-room, bedroom, arcade, office, classroom, garage, workshop; props window (sky, view), poster (sprite: one of the film's ids), shelf (items), clock (time), blackboard (lines), pegboard, plant, lamp, rug, desk (on), bed, sofa, cabinet (filing, arcade, locker), workbench, boxes, instrument. The TV, console and joystick stay (the identity); camera keys work as in room()",
  "scoreTable({ intent, at, until, title, rows: [{ who, score, locked }], hero, print, slam: { at, shake }, initials: 'arcade' | 'typed' | 'none', ring: { at, note }, prompt: { text, at }, enter: 'draw-in' | 'cut' })":
    'Breakthrough (toolkit, intent required): the attract-mode high-score table. Rows = the story`s facts in order of events, score = a real number / year, later events locked ???; the hero row slams in gold after a beat of silence (>= 0.4 s), initials scroll in, a grease pencil rings it on the glass, the prompt blinks (burned in); holds <= 4 s after its last beat. Returns { at, end, intent, cues }',
  "manual({ intent, at, until, title, steps: ['RULE ONE.', ...], figure: { caption, sprite | shape: 'box' | 'person' | 'house', layout: 'shelf' | 'pile' | 'queue', count, hit, callouts: [{ item, step }] }, ticks: [t], correction: { step, strike, write, at }, note: { text, at }, enter: 'slide' | 'cut', exit: 'turn' | 'cut' })":
    'Breakthrough (toolkit, intent required): the instruction-manual page over the frame (two-colour print, off-register plate, crease, coffee rings): <= 5 numbered rules, FIG. 1 = one of the film`s sprites (sprite: its id, printed in halftone) or a plain shape, pencil ticks that follow the narrator, at most ONE red correction only when the narration replaces a word (struck word, the narration`s word circled; never invented), a margin note; slides in (overshoot, cast shadow) and / or turns away from its corner; the HUD prints in paper ink on it',
  'calendarZoom({ intent, at, push, wipe })':
    'Continuity: the camera pushes into the room`s wall calendar, then the frame is redrawn line by line (interlaced) as the TV picture of the next place; returns landing = where the page stands in TV units ({ x: 96, y: 22, w: 46, h: 130 }): paint the next place`s page there. wipe: false = end on the page (world transition game-b1-scanline-wipe into the next shot)',
  "cartridge({ intent, action: 'insert' | 'pull', at, label, stripe, art, enter: 'pull-back' | 'cut', exit: 'push' | 'cut', hold })":
    'Continuity: the console close-up of the same room (its own floor: the interior`s, or the living room`s); the label`s art window is blank unless art = a sprite id of the film; the picture shrinks into the TV (pull-back), a hand brings a cartridge in (resists, clicks, garbage) or pulls it out (squeeze, garbage, the TV goes dark); push = back into the TV. Returns { at, end, intent, cues }',
  "levelSelect({ intent, at, until, nodes: [{ label, sprite | icon: 'home' | 'store' | 'pit' | 'office' | 'factory' | 'lock', x, y, above }], route: { from, to, at, dur } })":
    'The level-select map in the TV: the story`s places (sprite = the film`s own sprite for the place, or a plain icon) joined by dotted paths, the cartridge cursor hopping unevenly from node to node; lock = a place not reached yet (?)',
  "level({ intent, at, until, width, sky: [[y, colour]], ground: { y, colour, edge, field, pits: [[x0, x1]] }, platforms: [{ x, y, w, colour }], hero: { sprite, run: [[t, x]], jumps: [{ at, dur, height, onto }], fps }, things: [{ sprite, x, y, role: 'scenery' | 'item' | 'obstacle' | 'enemy' | 'goal', label, labelAt, appear, patrol: { to, period } }], camera: 'follow' | 'fixed', hitStop })":
    'GAMEPLAY (the main substance of a B1 film): a 2D level designed from the narration, played in the TV. The hero (one of the film`s sprites) runs on its keys in held steps, jumps in arcs (onto a ledge or back to the floor), the level scrolls in whole blocks when width > 160; items are collected on touch (sparkle), obstacles and enemies hit (hit-stop, flash, shake, the hero blinks) unless jumped, an enemy landed on from above is stomped, the goal blinks gold when reached; labels type over things. Every event is derived from the geometry (no state). Errors say what to change (a pit walked into, a ledge run off, a hero that never moves, fewer than 2 playable things). Returns { at, end, intent, cues, events: [{ t, kind, thing }], heroAt(t) }; call it first, then tv() for extras on top',
  "inventory({ intent, at, until, title, slots: [{ sprite, label }], cursor: [[t, slot]], craft: { a, b, at, reveal, result: { sprite, label } }, enter: 'blinds' | 'cut' })":
    'Breakthrough (toolkit, intent required): a game inventory of the narration`s parts (2-8 slots, the film`s sprites); the cursor hops on its beats, two parts lift into the crafting row (A + B ->), the result slot stays empty for a beat of silence, then the result pops in gold with its name typed; holds <= 4 s after the reveal. Returns { at, end, intent, cues }',
  "shop({ intent, at, until, title, wallet: { label, amount }, items: [{ sprite, label, price }], buys: [{ item, at }], keeper, enter: 'blinds' | 'cut' })":
    'Breakthrough (toolkit, intent required): a game shop for what something costs: 2-4 of the film`s things on a shelf with real prices, the wallet in the narration`s unit (MINUTES, DOLLARS, ENERGY); each buy hops the cursor, flies the item into the wallet and rolls it down; a buy the wallet cannot pay blinks NOT ENOUGH. Returns { at, end, intent, cues }',
  "splits({ intent, at, until, title, unit: 'clock' | 'DAYS', splits: [{ name, value, at, delta }], runner, enter: 'blinds' | 'cut' })":
    'Breakthrough (toolkit, intent required): a speedrunner`s split timer for a run of steps and their real values (cumulative; clock = seconds shown m:ss, or the narration`s unit): the big timer spins up and lands exactly on each value on its beat, the step prints with an optional delta (gold faster, crimson slower), the last split flashes gold; an optional runner sprite crosses the bottom. Returns { at, end, intent, cues }',
  "gameOver({ text: 'CONTINUE?' | 'GAME OVER', at, until, count: [[t, digit]], ghost })":
    'The game-over screen as the TV`s backdrop: black, the boss card burned in, CONTINUE? typed with a countdown (unequal holds) or GAME OVER slammed; tv() painters draw over it',
} as const;
