/**
 * Contact-sheet scenes of a film's world assets (PLAN.md#13.15 phase 2): generated standalone
 * scenes that draw each asset alone in a grid cell through the world's own scene API and
 * `ctx.worldAssets`, rendered like any scene (preview = export = sheet). One scene per page of
 * a kind: Sketchbook figures/props 8 per page, Comic characters/props 8 (backdrops 4, one panel
 * each), Game B2 sprites / textures 3 in an outdoor gallery (icons 6 in the inventory), Game B1
 * sprites 4 inside the TV (2 per scanline band), playfields 3, rooms 1.
 */
import type { WorldAssetSet } from '@reelforge/engine';
import type { WorldAssetWorld } from '@reelforge/shared';

/** Standalone shot id of a sheet scene (its file name). */
export const SHEET_SHOT_ID = 'world-assets';

export interface SheetPage {
  /** 1-based page number. */
  readonly page: number;
  /** Asset kind shown (`props`, `sprites`, …). */
  readonly kind: string;
  readonly ids: readonly string[];
  /** Grid columns (the thumbnail row scales a cell to <= 64 px wide). */
  readonly columns: number;
  /** Length of the standalone shot and the time rendered (everything drawn by then). */
  readonly duration: number;
  readonly time: number;
  readonly source: string;
}

interface Template {
  readonly perPage: number;
  readonly columns: number;
  readonly duration: number;
  /** Time rendered (default: just before the end, when everything is drawn). */
  readonly time?: number;
  readonly body: (kind: string, ids: readonly string[]) => string;
}

const UPDATE_ONE = (name: string): string => `export function update(t, state) {
  state.${name}.update(t);
}
`;

function header(world: WorldAssetWorld, kind: string, ids: readonly string[]): string {
  return `// Generated by reelforge world-assets sheet: the film's own ${world} ${kind}, each alone.
export const meta = { id: '${SHEET_SHOT_ID}', title: 'World assets', treatment: 'metaphor-object' };

const KIND = ${JSON.stringify(kind)};
const IDS = ${JSON.stringify(ids)};
`;
}

const SKETCHBOOK: Template = {
  perPage: 8,
  columns: 4,
  duration: 16,
  body: () => `
export function build(ctx) {
  const page = ctx.kit.fx.sketchPage({
    size: [ctx.shot.width, ctx.shot.height],
    duration: ctx.shot.duration,
    seed: 7,
    library: ctx.worldAssets,
  });
  ctx.scene.add(page);
  IDS.forEach((id, i) => {
    const x = 130 + (i % 4) * 235;
    const y = 250 + Math.floor(i / 4) * 255;
    if (KIND === 'figures') page.person({ like: id, x, y, h: 180, at: 0.2 + i * 0.2 });
    else page.use(id, { x, y, h: 180, at: 0.2 + i * 0.2, appear: 'bloom' });
  });
  return { page };
}

${UPDATE_ONE('page')}`,
};

const COMIC: Template = {
  perPage: 8,
  columns: 4,
  duration: 2,
  body: () => `
export function build(ctx) {
  const page = ctx.kit.fx.comicPage({ seed: 7, anchor: ctx.anchor, duration: ctx.shot.duration });
  ctx.scene.add(page);
  page.art.load(ctx.worldAssets);
  if (KIND === 'backdrops') {
    page.layout(IDS.map((id) => ({ at: 0, weight: 1, backdrop: id })));
    return { page };
  }
  IDS.forEach((id, i) => {
    const x = 8 + (i % 4) * 158;
    const y = 8 + Math.floor(i / 4) * 176;
    const w = 150;
    const h = 168;
    page.panel([x, y, x + w, y, x + w, y + h, x, y + h]).draw((g) => {
      page.art.draw(g, id, { x: x + w / 2, y: y + h - 10, size: h * 0.78 });
    });
  });
  return { page };
}

${UPDATE_ONE('page')}`,
};

const GAME_B2: Template = {
  perPage: 3,
  columns: 3,
  duration: 2,
  // The inventory is in (it slides out in the last 0.25 s of its span).
  time: 1.2,
  body: (kind) => `
const OPEN = ['.........', '.........', '.........', '.........', '.........', '.........', '.........'];
const WALLS = ['.........', '......a..', '.........', '......b..', '.........', '......c..', '.........'];

function level() {
  const base = { name: 'asset-sheet', sky: { preset: 'day' }, floor: 'concrete', lights: [] };
  if (KIND === 'textures') {
    const legend = {};
    IDS.forEach((id, i) => {
      legend['abc'[i]] = { wall: id, height: 1.5 };
    });
    const grid = WALLS.map((row) => row.replace(/[abc]/g, (ch) => (legend[ch] ? ch : '.')));
    return { ...base, grid, legend, sprites: [] };
  }
  const sprites = KIND === 'sprites' ? IDS.map((id, i) => ({ sprite: id, pos: [6.5, 2 + i * 1.5] })) : [];
  return { ...base, grid: OPEN, legend: {}, sprites };
}

export function build(ctx) {
  const size = [ctx.shot.width, ctx.shot.height];
  const view = ctx.kit.fx.b2View({
    size,
    level: level(),
    assets: ctx.worldAssets,
    duration: ctx.shot.duration,
    seed: 7,
    path: [{ at: 0, x: ${kind === 'textures' ? '1.5' : '0.4'}, y: 3.5, yaw: 0 }],
  });
  ctx.scene.add(view);
  let hud = null;
  if (KIND === 'icons') {
    hud = ctx.kit.fx.b2Hud({ size, view, duration: ctx.shot.duration, seed: 7 });
    hud.inventory({ items: IDS.map((id) => ({ icon: id, label: id.slice(0, 10).toUpperCase().replace(/-/g, ' ') })), at: 0 });
    ctx.scene.add(hud);
  }
  return { view, hud };
}

export function update(t, state) {
  state.view.update(t);
  if (state.hud) state.hud.update(t);
}
`,
};

const GAME_B1: Template = {
  perPage: 4,
  columns: 2,
  duration: 2,
  body: () => `
export function build(ctx) {
  const screen = ctx.kit.fx.b1Screen({
    size: [ctx.shot.width, ctx.shot.height],
    duration: ctx.shot.duration,
    seed: 7,
  });
  screen.assets(ctx.worldAssets);
  if (KIND === 'rooms') screen.interior(IDS[0]);
  screen.tv((g) => {
    g.rect(0, 0, 160, 180, 'cream');
    if (KIND === 'sprites') {
      IDS.forEach((id, i) => g.draw(id, 16 + (i % 2) * 80, 8 + Math.floor(i / 2) * 88, { frame: 0 }));
    }
    if (KIND === 'playfields') IDS.forEach((id, i) => g.field(id, 4 + i * 60));
  });
  ctx.scene.add(screen);
  return { screen };
}

${UPDATE_ONE('screen')}`,
};

const TEMPLATES: Readonly<Record<WorldAssetWorld, Template>> = {
  sketchbook: SKETCHBOOK,
  comic: COMIC,
  'game-b2': GAME_B2,
  'game-b1': GAME_B1,
};

/** Kinds shown per world, with their page size when it differs from the template's. */
const KINDS: Readonly<Record<WorldAssetWorld, readonly (readonly [string, number?])[]>> = {
  sketchbook: [['figures'], ['props']],
  comic: [['characters'], ['props'], ['backdrops', 4]],
  'game-b2': [['sprites'], ['textures'], ['icons', 6]],
  'game-b1': [['sprites'], ['playfields', 3], ['rooms', 1]],
};

/** The sheet pages of a set (no page for a kind without assets). */
export function worldAssetSheetPages(set: WorldAssetSet): SheetPage[] {
  const template = TEMPLATES[set.world];
  const pages: SheetPage[] = [];
  for (const [kind, size] of KINDS[set.world]) {
    const ids = set.ids.byKind[kind] ?? [];
    const perPage = size ?? template.perPage;
    for (let start = 0; start < ids.length; start += perPage) {
      const chunk = ids.slice(start, start + perPage);
      pages.push({
        page: pages.length + 1,
        kind,
        ids: chunk,
        columns: Math.min(template.columns, perPage),
        duration: template.duration,
        time: template.time ?? template.duration - 0.1,
        source: `${header(set.world, kind, chunk)}${template.body(kind, chunk)}`,
      });
    }
  }
  return pages;
}
