/**
 * Curated list of offensive words that must never appear on screen or in the narration
 * (real run Comic 1: CHINK as an onomatopoeia). English slurs and common profanity, lower case,
 * with the inflections that are checked (matching is whole-word: `chinking` and `chinkapin` are
 * not listed, so they pass). Homographs are listed on purpose and never allowed silently (a coon
 * is also a raccoon, a fag a cigarette, a dyke an embankment, `chink` a gap): a hit is an error
 * the author fixes by choosing another word. Keep the list short; `offensive-words.ts` matches.
 */

/** Ethnic, racial, sexual and disability slurs. */
export const SLUR_TERMS: readonly string[] = [
  'beaner',
  'beaners',
  'chinaman',
  'chinamen',
  'chink',
  'chinks',
  'chinky',
  'coon',
  'coons',
  'dago',
  'dagos',
  'dyke',
  'dykes',
  'fag',
  'faggot',
  'faggots',
  'fags',
  'gook',
  'gooks',
  'gyppo',
  'honkies',
  'honky',
  'injun',
  'injuns',
  'jigaboo',
  'kike',
  'kikes',
  'nigga',
  'niggas',
  'nigger',
  'niggers',
  'paki',
  'pakis',
  'raghead',
  'ragheads',
  'redskin',
  'redskins',
  'retard',
  'retarded',
  'retards',
  'shemale',
  'spaz',
  'spic',
  'spics',
  'squaw',
  'towelhead',
  'towelheads',
  'trannies',
  'tranny',
  'wetback',
  'wetbacks',
  'wop',
  'wops',
  'zipperhead',
];

/** Common profanity. */
export const PROFANITY_TERMS: readonly string[] = [
  'asshole',
  'assholes',
  'bitch',
  'bitches',
  'bullshit',
  'cocksucker',
  'cunt',
  'cunts',
  'dickhead',
  'fuck',
  'fucked',
  'fucker',
  'fuckers',
  'fuckin',
  'fucking',
  'fucks',
  'horseshit',
  'motherfucker',
  'motherfuckers',
  'shit',
  'shits',
  'shitting',
  'shitty',
  'slut',
  'sluts',
  'twat',
  'wanker',
  'wankers',
  'whore',
  'whores',
];
