/**
 * Launchers that put `reelforge` on PATH for the spawned Claude Code: the app writes them into a
 * folder of its own and the bridge prepends that folder to PATH. Claude's Bash tool runs Git Bash
 * on Windows, which needs the extension-less `reelforge` sh script; cmd/PowerShell use
 * `reelforge.cmd`. Paths may contain spaces and non-ASCII letters.
 */
import { chmod, mkdir, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';

/** The bundled CLI (built by `pnpm --filter @reelforge/cli build`). */
export const CLI_BUNDLE_PATH = path.resolve(import.meta.dirname, '..', 'dist', 'reelforge.mjs');

export interface CliShimOptions {
  /** Folder to write the launchers into (goes on PATH). */
  readonly dir: string;
  /** Node-compatible executable (node.exe, or the app's Electron binary with ELECTRON_RUN_AS_NODE=1). */
  readonly runtime: string;
  /** The CLI script; defaults to CLI_BUNDLE_PATH. */
  readonly script?: string;
  /** Extra environment for the runtime, e.g. `{ ELECTRON_RUN_AS_NODE: '1' }`. */
  readonly env?: Readonly<Record<string, string>>;
  /** Defaults to the current platform; `win32` also writes reelforge.cmd. */
  readonly platform?: NodeJS.Platform;
}

const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;
/** Characters that cannot be quoted safely in both sh and cmd. */
const UNSAFE = /["%!`$\r\n]/;

function assertSafe(label: string, value: string): void {
  if (UNSAFE.test(value)) {
    throw new Error(
      `reelforge shim: ${label} contains a character that cannot be quoted safely ("%!\`$ or a newline): ${value}`,
    );
  }
}

function checkedEnv(env: Readonly<Record<string, string>>): [string, string][] {
  return Object.entries(env).map(([name, value]) => {
    if (!ENV_NAME.test(name))
      throw new Error(`reelforge shim: invalid environment variable name "${name}"`);
    assertSafe(`env ${name}`, value);
    return [name, value];
  });
}

/** POSIX sh launcher (also Git Bash on Windows, which accepts C:/... paths). */
export function shShim(
  runtime: string,
  script: string,
  env: Readonly<Record<string, string>> = {},
): string {
  assertSafe('runtime', runtime);
  assertSafe('script', script);
  const posix = (value: string): string => value.split('\\').join('/');
  const exports = checkedEnv(env).map(([name, value]) => `export ${name}="${value}"\n`);
  return `#!/bin/sh\n# Generated by @reelforge/cli (writeCliShims); do not edit.\n${exports.join('')}exec "${posix(runtime)}" "${posix(script)}" "$@"\n`;
}

/**
 * cmd.exe launcher. cmd reads batch files in the console code page, so a file with non-ASCII
 * paths switches to UTF-8 (65001) for the call and restores the previous code page afterwards.
 */
export function cmdShim(
  runtime: string,
  script: string,
  env: Readonly<Record<string, string>> = {},
): string {
  assertSafe('runtime', runtime);
  assertSafe('script', script);
  const sets = checkedEnv(env).map(([name, value]) => `set "${name}=${value}"\r\n`);
  const call = `"${runtime}" "${script}" %*\r\n`;
  // eslint-disable-next-line no-control-regex -- detecting non-ASCII characters is the point
  const ascii = /^[\x00-\x7f]*$/.test(runtime + script + sets.join(''));
  const body = ascii
    ? `${sets.join('')}${call}exit /b %ERRORLEVEL%\r\n`
    : [
        'for /f "tokens=*" %%a in (\'chcp\') do for %%b in (%%a) do set "REELFORGE_CP=%%~nb"\r\n',
        'chcp 65001 >nul\r\n',
        ...sets,
        call,
        'set "REELFORGE_EXIT=%ERRORLEVEL%"\r\n',
        'chcp %REELFORGE_CP% >nul\r\n',
        'exit /b %REELFORGE_EXIT%\r\n',
      ].join('');
  return `@echo off\r\nrem Generated by @reelforge/cli (writeCliShims); do not edit.\r\nsetlocal\r\n${body}`;
}

async function writeAtomic(file: string, content: string): Promise<void> {
  const temporary = `${file}.${String(process.pid)}.tmp`;
  await writeFile(temporary, content, 'utf8');
  await rename(temporary, file);
}

/** Writes the launchers and returns their paths. */
export async function writeCliShims(options: CliShimOptions): Promise<string[]> {
  const script = path.resolve(options.script ?? CLI_BUNDLE_PATH);
  const runtime = path.resolve(options.runtime);
  const env = options.env ?? {};
  await mkdir(options.dir, { recursive: true });
  const sh = path.join(options.dir, 'reelforge');
  await writeAtomic(sh, shShim(runtime, script, env));
  await chmod(sh, 0o755);
  if ((options.platform ?? process.platform) !== 'win32') return [sh];
  const cmd = path.join(options.dir, 'reelforge.cmd');
  await writeAtomic(cmd, cmdShim(runtime, script, env));
  return [sh, cmd];
}
