import { spawnSync } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { cmdShim, shShim, writeCliShims } from './shims.js';

let base: string;

beforeAll(async () => {
  base = path.join(await mkdtemp(path.join(tmpdir(), 'reelforge shims ')), 'Zażółć gęślą');
});

afterAll(async () => {
  await rm(path.dirname(base), { recursive: true, force: true });
});

/** A stand-in CLI script: prints its arguments and the shim's env, exits with code 3. */
const ECHO_SCRIPT = `process.stdout.write(JSON.stringify({ args: process.argv.slice(2), env: process.env.REELFORGE_SHIM_TEST ?? null }));
process.exitCode = 3;
`;

describe('shim text', () => {
  it('sh: forward slashes, quoted paths, env exports, "$@"', () => {
    const text = shShim('C:\\Program Files\\node.exe', 'C:\\a b\\reelforge.mjs', {
      ELECTRON_RUN_AS_NODE: '1',
    });
    expect(text).toBe(
      '#!/bin/sh\n# Generated by @reelforge/cli (writeCliShims); do not edit.\nexport ELECTRON_RUN_AS_NODE="1"\nexec "C:/Program Files/node.exe" "C:/a b/reelforge.mjs" "$@"\n',
    );
  });

  it('cmd: CRLF, plain call for ASCII paths, UTF-8 code page switch otherwise', () => {
    const ascii = cmdShim('C:\\node.exe', 'C:\\x\\reelforge.mjs');
    expect(ascii).toContain('"C:\\node.exe" "C:\\x\\reelforge.mjs" %*\r\nexit /b %ERRORLEVEL%');
    expect(ascii).not.toContain('chcp');
    const polish = cmdShim('C:\\node.exe', 'C:\\Zażółć\\reelforge.mjs');
    expect(polish).toContain('chcp 65001 >nul\r\n');
    expect(polish).toContain('chcp %REELFORGE_CP% >nul\r\nexit /b %REELFORGE_EXIT%');
  });

  it('refuses characters that cannot be quoted and bad env names', () => {
    expect(() => shShim('C:\\a"b\\node.exe', 'x.mjs')).toThrow(/cannot be quoted safely/);
    expect(() => cmdShim('node.exe', 'C:\\100%\\x.mjs')).toThrow(/cannot be quoted safely/);
    expect(() => shShim('node', 'x.mjs', { 'BAD-NAME': '1' })).toThrow(/invalid environment/);
  });
});

describe('writeCliShims', () => {
  it('writes launchers that run the script with arguments, env and exit code', async () => {
    const script = path.join(base, 'app dir', 'fake-reelforge.mjs');
    await mkdir(path.dirname(script), { recursive: true });
    await writeFile(script, ECHO_SCRIPT);
    const dir = path.join(base, 'bin dir');
    const written = await writeCliShims({
      dir,
      runtime: process.execPath,
      script,
      env: { REELFORGE_SHIM_TEST: 'tak' },
    });
    const windows = process.platform === 'win32';
    expect(written.map((file) => path.basename(file))).toEqual(
      windows ? ['reelforge', 'reelforge.cmd'] : ['reelforge'],
    );
    expect(await readFile(path.join(dir, 'reelforge'), 'utf8')).toMatch(/^#!\/bin\/sh\n/);
    const run = windows
      ? spawnSync(
          'cmd.exe',
          ['/d', '/s', '/c', `"call "${path.join(dir, 'reelforge.cmd')}" status --at "0, 2.5""`],
          { windowsVerbatimArguments: true, encoding: 'utf8' },
        )
      : spawnSync(path.join(dir, 'reelforge'), ['status', '--at', '0, 2.5'], { encoding: 'utf8' });
    expect(run.status).toBe(3);
    expect(JSON.parse(run.stdout)).toEqual({ args: ['status', '--at', '0, 2.5'], env: 'tak' });
  });
});
