/**
 * Turntable of a project prop (PLAN.md#7.4): a generated standalone scene that shows the prop
 * alone on a neutral stage, one view angle per second, and reports `kit.voxel.inspect(prop)` as
 * an sfx cue (the one value channel every render path - Playwright and the app's render service
 * - returns from a scene build). Rendered like any scene, so preview = export = prop preview.
 */
import type { RgbaImage } from '@reelforge/engine/raster';
import { composeSheet, type SheetRow } from '../render/sheet.js';

/** Default view angles (degrees, 0 = front facing the camera). */
export const DEFAULT_ANGLES: readonly number[] = [0, 90, 180, 270];
/** Cue name prefix of the inspection data (`prop-metrics {json}`). */
export const METRICS_CUE = 'prop-metrics ';
/** Standalone shot id of the turntable scene (its file name). */
export const TURNTABLE_SHOT_ID = 'turntable';

/** Project-relative files of a prop's preview (git-ignored app data). */
export function propPreviewPaths(name: string): { scene: string; sheet: string; dir: string } {
  const dir = `.reelforge/frames/props/${name}`;
  return { dir, scene: `${dir}/turntable.js`, sheet: `${dir}/turntable.png` };
}

/** Local times rendered: angle i at i + 0.5 s, then angle 0 again (determinism check). */
export function turntableTimes(angles: readonly number[]): number[] {
  return [...angles.map((_, index) => index + 0.5), angles.length + 0.5];
}

/** Length of the standalone turntable shot (s). */
export function turntableDuration(angles: readonly number[]): number {
  return angles.length + 1;
}

/** The scene module (lint-clean, deterministic) that shows `kit.props.<name>()` turning. */
export function turntableSource(name: string, angles: readonly number[]): string {
  return `// Generated by reelforge prop-preview: the prop ${name} alone, one view per second.
export const meta = { id: '${TURNTABLE_SHOT_ID}', title: 'Prop ${name}', treatment: 'metaphor-object' };

const NAME = ${JSON.stringify(name)};
const ANGLES = ${JSON.stringify(angles)};

export function build(ctx) {
  const { kit, scene, three, palette, sfx } = ctx;
  scene.background = new three.Color(palette.sky);
  scene.add(kit.env.lights());
  const make = kit.props[NAME];
  if (typeof make !== 'function') {
    throw new Error('kit.props.' + NAME + ' is not registered: kit-ext/props/' + NAME + '.js did not load');
  }
  const prop = make();
  const report = kit.voxel.inspect(prop);
  sfx.at(0, '${METRICS_CUE}' + JSON.stringify(report));
  const box = prop.bounds();
  const center = box.getCenter(new three.Vector3()).multiply(prop.scale);
  const pivot = kit.voxel.group();
  prop.position.set(-center.x, -box.min.y * prop.scale.y, -center.z);
  pivot.add(prop);
  const [w, h, d] = report.size;
  const reach = Math.max(Math.hypot(w, d), 0.2);
  const plate = kit.voxel.mesh(kit.voxel.box([16, 1, 16], 'groundAlt'), {
    voxelSize: (reach * 1.3) / 16,
    pivot: [8, 1, 8],
  });
  scene.add(plate, pivot);
  const dist = Math.max(1.65 * h, 0.95 * reach, 1.2);
  return { pivot, h, dist };
}

export function update(t, s, ctx) {
  const index = Math.min(Math.floor(t), ANGLES.length) % ANGLES.length;
  s.pivot.rotation.y = (ANGLES[index] * Math.PI) / 180;
  ctx.camera.set({ position: [0, s.h * 0.55 + s.dist * 0.35, s.dist], target: [0, s.h * 0.45, 0] });
}
`;
}

export interface TurntableFrame {
  /** Local shot time. */
  readonly t: number;
  readonly image: RgbaImage;
}

/** 2 views per row, labelled "<name> <angle>°", native pixels (for Claude and the critic). */
export function turntableSheet(
  name: string,
  angles: readonly number[],
  frames: readonly TurntableFrame[],
  size: { readonly width: number; readonly height: number },
): RgbaImage {
  const tiles = angles.map((angle, index) => {
    const frame = frames.find((candidate) => Math.abs(candidate.t - (index + 0.5)) < 1e-6);
    return frame
      ? { label: `${name} ${String(angle)} deg`, frame: frame.image }
      : { label: `${name} ${String(angle)} deg`, failure: 'NOT RENDERED' };
  });
  const rows: SheetRow[] = [];
  for (let index = 0; index < tiles.length; index += 2) {
    rows.push({ tiles: tiles.slice(index, index + 2) });
  }
  return composeSheet(
    {
      title: `prop ${name} - turntable (kit-ext/props/${name}.js)`,
      frameWidth: size.width,
      frameHeight: size.height,
      factor: 1,
    },
    rows,
  );
}
