/**
 * Embedded world geodata of the blueprint map: Natural Earth 1:110m Admin 0 countries (public
 * domain, naturalearthdata.com, docs/licenses.md), outer rings only, simplified for this repo:
 * topology-preserving Douglas-Peucker (0.5 degrees; border junctions stay fixed and shared
 * borders simplify identically, so neighbours still tile without slivers), islands under 1 square
 * degree dropped except a country's largest ring, snapped to a 0.25-degree grid and stored as
 * encoded polylines (the Google polyline algorithm: zigzag deltas, 5-bit chunks, chars 63..126).
 * About 13 KB for 177 countries. Made with Natural Earth.
 * Rows: [ADM0_A3 code, continent (AF AN AS EU NA OC SA SS), name, rings].
 */

/** Degrees per stored unit. */
export const WORLD_QUANTUM = 0.25;

export type CountryRow = readonly [string, string, string, readonly string[]];

// prettier-ignore
export const WORLD_COUNTRIES: readonly CountryRow[] = [
  ['FJI', 'OC', 'Fiji', ['qk@jCADF?']],
  ['TZA', 'AF', 'Tanzania', ['oGFi@\\?\\GLTHP?D?@IBEFABAFCBAHU@GC?EM?AAE@CAAG?']],
  ['SAH', 'AF', 'W. Sahara', ['dA}E?@?JX??TD?@N^@?CQ?Yk@U??E']],
  ['CAN', 'NA', 'Canada', ['t]gKd@M@KJCHOCIj@]NDZI?kAc@D{@EEESFIEADUAq@DIBHBM@[AGBICFACCO?e@FW??EE?M@@FOMPG?IIEQDKFFBO@?FIEID@DGBMK?IW@IBDFCH`@BJLZHZRBNK@GLoAL?NQNKIHQYMNQIGDSa@Aa@JANKDYOWX@Dc@JKJ?F`@Nr@?NHRPo@SEBDDCLW@GGEFj@RD?@GMET?BMJCPRX?~@XA[n@WX?VI', 'tRaQGCgAPMHLBw@NPLTKH@@B[P@D\\GSLd@G\\MVBDACE_@AIMBEl@QlAADAGCJ?@GMIUADBED[IMF@D', 'zUoSaBIkCBn@HQ?l@Ll@BK?D@EB`@HMBRBfAAMEBEYBVEWGNGi@Al@?', 'rYgQG@GL[FLBADtA@^Ke@Aj@ABCSAZAa@MG@B@e@AMHCADG', 'j]sQo@Fz@RVEOOFC', '~VcS[Eu@NXF^?FCEEZE', '`UsQ`@AJKVCk@?QH_AAIBBB', 'zLyKHJYB@DEAAH@DH??GHDDEV@OY', '|Y}QMA@Fn@BJAOCn@?QIs@FJGGA', 'bXeQFCICU?BDKB@DJB`@I', '~SgO_@HVARFLCIQ', 'rVqQ_@Bf@LBK', 'rWeREBBH`@C?E', 't]_R]KUADH', 'z]cKPAROSB', 'jYyRe@BGDj@CGA', '|ReQHCEC_@F', '`WkPCBB@ZEKE', 'jVwQX?OE', 'dWuRI@LDJG', 'xQ{ON?IE', 'xZqRGBX?', 'd`@oLG?@FEDLI', 'rYkQO?FD', '~SsNECI??@FBD?']],
  ['USA', 'NA', 'United States of America', ['t]gK_FCWHY?o@V@Z_AYY?QSKBCLZPEH\\DM?N@FLBCCFFH@O?HDAITj@^Ib@BLHCNa@H@JEV@?Fh@ARL@NJCNYV@RSb@B\\KR@HKNC^m@Ci@DUM@CF', 'r_@uLZYTAVIx@KH@AD\\DIOZNEBFB`@Pr@Jq@SMOf@@BITCDGACII]CDEEA`@@VI[EUBf@QCEmAQ{BJ?jA[HOEk@\\', 'he@oMGBPB', '|i@}NE@CAE@G@D@DABAD@@A']],
  ['KAZ', 'AS', 'Kazakhstan', ['yTiKDDD?BJNADLRBELB@?DBAj@EDDPA@BB@PHJCDMFEV@ZORB?\\B?JGJB?GPMUE?K^@ROGOGDQOg@Hk@AACJEMGDECA{@KM@CFQ@?B[GW\\[AOHI?']],
  ['UZB', 'AS', 'Uzbekistan', ['_MiI?]SC[NWAGDELKBQICAA?DDSDHBD?B?AEJ@DHD?EHDFD?B??E|@e@LJ']],
  ['PNG', 'OC', 'Papua New Guinea', ['gb@R[HYPBJ[TT?XSNJLA', 'yd@l@JBJCOECBKI', 'ee@\\?FNO']],
  ['IDN', 'AS', 'Indonesia', ['o\\a@DFMPH@Jd@n@GH[EKEHYCEAIU', 'aYFMN@TF?XWp@aAQ@YXMBIJ@D', 'gb@R?r@DET@IIDM`@ODBFIMCJ?LI[ACNGBOK', 'w]GOEBH`@@@DGFQGLJMXF?CEH?BMD@ARD@FWGWIG', 'cZr@_@BYHHB~@KHCEE', '__@QEFDPBO', 'i_@TKFTA', 'i]bAE?GC@DJ@HA?AEA', 'g^fA?BJD', 'q\\`AGBR@']],
  ['ARG', 'SA', 'Argentina', ['lMpF?DDVMVRLV??NB@P??FKBLF@JLB@DMFZZEJZAJUIGG[FSK]@MISDWEUKK@SKK?AEGMFCEI??@OLWHDLOBMG?ECACJRL', 'dPdLGFUFN@LA']],
  ['CHL', 'SA', 'Chile', ['jPjCCDIb@E??@JJARJJDTEVHRALJ\\GRFZHFKT[@PD@DJARIB[IMJAKUGBCODC@HB?G_@@OOe@KwA@YCA', 'dPdL?NM@HBTC\\Q]HEG']],
  ['COD', 'AF', 'Dem. Rep. Congo', ['iFb@AFITB?LF@RIBAFRMVC@?BAH@B]LAFFJ?HO^?EIK@KKSs@?C?EGEWFOGSAA?EDO@EDCHLT?D@@@D?BAB']],
  ['SOM', 'AF', 'Somalia', ['kILBc@EICAUEUWEECUOCJh@V^']],
  ['KEN', 'AF', 'Kenya', ['yHd@h@]?GGOBKBECCEEC@CDMFYCC?DHCb@']],
  ['SDN', 'AF', 'Sudan', ['cEaADCDO@CAAFGAMEKG@@_@?CI??O_@?}@?EZGBLFBPA@@FP^?D?EHUJRHCFDP?FGLN']],
  ['TCD', 'AF', 'Chad', ['}D{CA^FADJ@LGF@@B@HJf@ND?AAJMKCBQBC?CFGMSE]FE@KGE_@N']],
  ['HTI', 'NA', 'Haiti', ['|P}C?LTAQCFI']],
  ['DOM', 'NA', 'Dominican Rep.', ['|PoC?M[H']],
  ['RUS', 'EU', 'Russia', ['gKsJPNMTDBFC@?DAl@KXMKGBCKAF?KGAKd@GJMJ@B?BGKANK?EJCFABC?CBACAAMGCFC[QJECEFEEEHIGEJC?EGAKAk@Bc@JADTDh@EKDAJODBGECQDGADEQGOBCEFMU@CBHDE@{@OE?FBi@EIDGEFCCA_ALECPG@KYOUDFDGF@JIBRPI?SKBCCEJEGGJEOC@EGBBFG?@CKC_@BFOq@ADCICkBK[IWH]AYFd@JmBH?E]@KBCBBBUHGG{@@BGIAgAB[Jo@?EFI@u@?MDIADECA_ABKB?^RBMJ?Dj@BZLHCj@DJJID@HHFABLB@FJ@LNHc@CI}@c@EIb@NDIR@RLEB\\B?EJAz@Dv@`@WFMCIHHb@h@f@HDHCJF?A?CAOOAOY^DJMLALWREXDCDTRHCH@HCZFP?JGX@f@OJPf@GZHF@B?BCH?NIZ@V]ZF?CPABGLAz@JB@EDLFKD@Bj@@f@IPNFEFN', 'kLmQSG@Ak@I{@ApAPVN?DODn@EGIOG', 'vj@yOEF@EU?MFRBBHh@IBCH@C@BB?_@', 'mVgSQAa@J@Df@?\\I', 'wb@mLMd@JADJGJDCDD@y@EC@C', 'ua@aRq@DDDh@@NE', 'uXyRQFj@@MI', 'kGoJK@IDPDJG', 'eJcSu@A^D', 'uDqLL?HAKEKD', 'ad@yQS@T@NC', '}a@iQQCKB', 'tk@wPH@?ES@']],
  ['BHS', 'NA', 'Bahamas', ['pRiEA?CF?B@?@CBA']],
  ['FLK', 'SA', 'Falkland Is.', ['hN|KUEEBLD']],
  ['NOR', 'EU', 'Norway', ['wFkPJ@F@CET?JFZCB@D??BXBX^F?BDAXHHDELHTAD[k@Sa@Yc@Oi@I]AWDH@', 'yB}RMAc@FRBNLF?j@W', '{E_Sb@Bl@E', 'eEmR^?EADAQA']],
  ['GRL', 'NA', 'Greenland', ['tJuSaAE{A?q@DtADcA?G@HB{@E[D|@FQ?NJ?FIDX@ODADH?KF`@FIFR?SDCDL@NGADFB_@?jCd@JNJDADFNH?ZEZWP[YU^BCIU@`@IGE\\WnACVGe@Cr@C{@KPCm@IBCaBEo@D']],
  ['ATF', 'SS', 'Fr. S. Antarctic Lands', ['gPbKKDLB']],
  ['TLS', 'AS', 'Timor-Leste', ['g^fAQCPF']],
  ['ZAF', 'AF', 'South Africa', ['aCbFCCMFKC?]A@ELC?MKS@QUKEA?G@C?CJ?L?@B?BFGBACE?BN^^RHXARFJC@S']],
  ['LSO', 'AF', 'Lesotho', ['gFfFFJFC']],
  ['MEX', 'NA', 'Mexico', ['h\\cGSA]Jc@CSRWAOXKB@XM\\KBWEIOYCDXBAFB?@D?JBGHH?BJLKR@bA[F[XU?GVSJSFA?Ji@v@BBPO?ITMEE']],
  ['URY', 'SA', 'Uruguay', ['lMpFEAYNCLLHZGEW']],
  ['BRA', 'SA', 'Brazil', ['hLlGBMXOD@KKSMBKB@ACAIH?@MPAAIBCCAAMDON?@Sf@QAMZHD?B?BKLBFCDOGQQGE?CUBOECBEQACDEBWKFABKM@SI@AC?CZIBMCAAC@?EG?C@C@G?IQMRBLO@?FEEUFCHc@?c@RENBLZ^Bd@L`@FFl@NH\\']],
  ['BOL', 'SA', 'Bolivia', ['jPvAE?[I@Lg@PARO?EN@LB@?CZ?BHBH?AH?BDLGDFD?Hc@BECGA_@']],
  ['PER', 'SA', 'Peru', ['nP`@D?PFFPENGBMCCJC?EJ@^BF@BB@l@[\\{@JG@KII@FIB_@_@?EAAOPWBBF']],
  ['COL', 'SA', 'Colombia', ['vOIBEP@CDDBCNBTBCCGVCNQ@@BAVKKQD[EKKEEKYKCDNRIPe@FBXCB']],
  ['PAN', 'NA', 'Panama', ['hReADJFMJD?FRGCIGDSE']],
  ['CRI', 'NA', 'Costa Rica', ['rSkABHTM?GO?']],
  ['NIC', 'NA', 'Nicaragua', ['|SwAN?JOQMMA']],
  ['HND', 'NA', 'Honduras', ['xSwBL@PLBCHE@A?AGGYA']],
  ['SLV', 'NA', 'El Salvador', ['hUsBA@IDPACC']],
  ['GTM', 'NA', 'Guatemala', ['`VsBCKI?FIKCE??DAFE@FF?@@@BB']],
  ['BLZ', 'NA', 'Belize', ['hUmC?AGCDR@G']],
  ['VEN', 'SA', 'Venezuela', ['dNi@A@RHLACJG@VJDC@GBCCYd@GHQOSD@AREEBIKIMLYBWED@ABULLP']],
  ['GUY', 'SA', 'Guyana', ['bMO@@LBHCB[B?DEMQSPDNEH']],
  ['SUR', 'SA', 'Suriname', ['rLQBAF??DBADEDIEOY@@V']],
  ['FRA', 'EU', 'France', ['q@kKC@I@BD?D@?HDC@AB?@ENb@D?Bf@GESXO?EW?BGGB[OQHGBA?', '|Ka@HPF?BAACAW', 'eAuIEA@J']],
  ['ECU', 'SA', 'Ecuador', ['xQ@?D^^HCAGCEHC?IGMIEWJ']],
  ['PRI', 'NA', 'Puerto Rico', ['pOsCCBJ?']],
  ['JAM', 'NA', 'Jamaica', ['jRsCIBJ@BC']],
  ['CUB', 'NA', 'Cuba', ['pSyD_@D_@PZBEELGVIXD']],
  ['ZWE', 'AF', 'Zimbabwe', ['yFpDB?FA@?DAVYBEI?WOEA?BSDB`@']],
  ['BWA', 'AF', 'Botswana', ['kFnDJDPTRALJB?DM@A?WG??[[ACAA?CDWX']],
  ['NAM', 'AF', 'Namibia', ['_DdE?\\JBLGBBFKFg@Re@mADMCEAG@?@B@Z@?ZF?']],
  ['SEN', 'AF', 'Senegal', ['dCkBFIIKOAMHCDABCH?@@?J?B?LAH@?EWA']],
  ['MLI', 'AF', 'Mali', ['zAcB?ABI@CCA?Eq@?FkAK?[Pe@\\GA?RBHTBD?B?\\JJR?D@?P?@AFMP@']],
  ['MRT', 'AF', 'Mauritania', ['fCgD_@AAOE??UY??K]RJ?GjAp@??DB@BELIN@A]']],
  ['BEN', 'AF', 'Benin', ['Uq@F??WFIACA?EEAAAAA?EB?B']],
  ['NER', 'AF', 'Niger', ['uBuDAJGDD\\LRGF?B@??@@?FG^DZGH?BH@DDC@?@@?EH?DM?CE?UCCI?SKAUO[OKBEB']],
  ['NGA', 'AF', 'Nigeria', ['Uq@Eg@?CAECII?[F_@EGFA?ABTf@RBDLRBLO']],
  ['CMR', 'AF', 'Cameroon', ['sBeBCBCPJBKL@@BF@LKP?@?BLCH?H?B?J?HSEMSCUg@@C?A']],
  ['TGO', 'AF', 'Togo', ['GwA@BGH?VD@Fe@?A']],
  ['GHA', 'AF', 'Ghana', ['?wA?@Gd@\\FBIEO@K@E?CS?']],
  ['CIV', 'AF', 'Côte d\'Ivoire', ['~@qAQ?A?C?K@E@AJDNCHf@DDY?AA??S']],
  ['GIN', 'AF', 'Guinea', ['lBcBC?K?A??BQAGLA@@??R@?@?BBDI@?@@BMPFNOKI']],
  ['GNB', 'AF', 'Guinea-Bissau', ['dCcBIAM@?@JH']],
  ['LBR', 'AF', 'Liberia', ['bA}@?@EX\\SEICCA?EHCC']],
  ['SLE', 'AF', 'Sierra Leone', ['hBgAQGCLAABBDH']],
  ['BFA', 'AF', 'Burkina Faso', ['j@qA?EKS]KC??BELI??D@@DD@?F?B?R??BADDAJA']],
  ['CAF', 'AF', 'Central African Rep.', ['yEi@@?R@NFVGFD?DD?H@BF?AJQAMCGE?g@OIKCAABENEBCBQP']],
  ['COG', 'AF', 'Congo', ['sC[?BRr@JJJAF@FGKOM??YHC?CI?MB?CCGIA']],
  ['GAB', 'AF', 'Gabon', ['yAQC?I??BIB?XL?JNPWEOM?']],
  ['GNQ', 'AF', 'Eq. Guinea', ['mAQK??HL?']],
  ['ZMB', 'AF', 'Zambia', ['uF`AC@GBC@CBB^C@VD?DD@VNH?@??AFAD@DCBG?WO??M?AA?WBSL@GHCASMG']],
  ['MWI', 'AF', 'Malawi', ['eGhAG@CDAH@DK\\DDBQD?BCBAC_@']],
  ['MOZ', 'AF', 'Mozambique', ['sGzAE?Q?UIAh@l@`@E^VNAFD??C@C?A?MBKGICa@RE?C?EWECBE?CPEEJ]']],
  ['SWZ', 'AF', 'eSwatini', ['_GtE@BFCCGC?AB']],
  ['AGO', 'AF', 'Angola', ['aBn@_@?INK?GGM@C\\IAC@?@?LN??VCFEBLBlAEOo@']],
  ['BDI', 'AF', 'Burundi', ['sFR?@DLB??I@CE@AE']],
  ['ISR', 'AS', 'Israel', ['}GeG@@@?@HCA?BBJ@ABKGMAAA??B']],
  ['LBN', 'AS', 'Lebanon', ['}GiG@?@@EMCBBB']],
  ['MDG', 'AF', 'Madagascar', ['kKbBGXD?ThAJBJCDQIYBOCIMCW]']],
  ['PSX', 'AS', 'Palestine', ['{G{FB@AIA??D']],
  ['GMB', 'AF', 'Gambia', ['dCkBI??ACAA@A?C?A@B@B?BA@@@?@?D?']],
  ['TUN', 'AF', 'Tunisia', ['kAqFBMJIG]S?DTIFJT']],
  ['DZA', 'AF', 'Algeria', ['dA{E?A?G{@[FW]Iw@CF\\KHCLADBZGJIBCBZNTNJ@F@d@]ZQ']],
  ['JOR', 'AS', 'Jordan', ['{GcGAAGBOICH@@NBGFBBRD?ACK?C?A']],
  ['ARE', 'AS', 'United Arab Emirates', ['{KaES@OOCFHN?@@@VC']],
  ['QAT', 'AS', 'Qatar', ['uKeECIAH']],
  ['KWT', 'AS', 'Kuwait', ['_KoFCJFCF?EG']],
  ['IRQ', 'AS', 'Iraq', ['yHaGBIQGEOCECAKBCAEHEFDFMJIRB?D?DFLA`@U']],
  ['OMN', 'AS', 'Oman', ['yLuD?AIOYTNN?Hd@P@CDMWGEO']],
  ['VUT', 'OC', 'Vanuatu', ['uh@|B?A?EA@AD@A']],
  ['KHM', 'AS', 'Cambodia', ['sXaB@IOGG@E@CCG@?D?HLDCBNB']],
  ['THA', 'AS', 'Thailand', ['iYqBFANFAHRIDZIRMHFBHEJO@DAQGOHWEIJQOMCACBEB@NWEKZ']],
  ['LAO', 'AS', 'Laos', ['{YqBFABBDAACJ[VDAODCBCAAGE?@C??GCACDCFI?ADDD[^']],
  ['MMR', 'AS', 'Myanmar', ['_XcDB@NLKPDHIVFN?WH_@NHFA?QNSCC?ECA?ME@GUQCAG@AE?EPHNI?EF@FO@?@FD']],
  ['VNM', 'AS', 'Vietnam', ['aYsAOCBCME?I?E?GZ_@EE@EH?BGBECASCULPRY\\AZ^X']],
  ['PRK', 'AS', 'North Korea', ['u_@sI?@XREHNDJAEKHCm@W']],
  ['KOR', 'AS', 'South Korea', ['q^mHOEILBLRBBQEA']],
  ['MNG', 'AS', 'Mongolia', ['}TiKGA[Ig@FKQg@NYAKFQ?[GIBIABDBJQAMHP?^NLABBCDHFj@H`@Ib@?FK`@GDSPE']],
  ['IND', 'AS', 'India', ['iWaFA@@FPBFTDA?LB@BMBDBCIKRAJI@DEBFDGRNBBH`@\\NBBl@PP^_ADi@P@PUUCJUGGI?[a@JOWCGEIHALD?IJIDBBBFi@NU@?G?CE??D?@Y@?E@AEAOIKAAF']],
  ['BGD', 'AS', 'Bangladesh', ['eVoD?DBBDOF?@FHAFSGEDCAEKHS@HJCBCE']],
  ['BTN', 'AS', 'Bhutan', ['}U}EA@?DXA?AEEM?']],
  ['NPL', 'AS', 'Nepal', ['_U_F?B?FTAh@OCGCCCAk@R']],
  ['PAK', 'AS', 'Pakistan', ['mR{GFDVBKNZ`@H?FFKTTBNMd@BAIKCNSBCMB]EEIQEGI@EG?CI@EYGEAEBAD']],
  ['AFG', 'AS', 'Afghanistan', ['sOiHC?E?C@SKGLQEG?A@D@XFADBHF?ADFHPDDH\\DLCGGHQAKCIGB_@Q']],
  ['TJK', 'AS', 'Tajikistan', ['}OiHEGDIE?EIKA@DC?@@H??BQ@OAAFEBABF?PDFMRJ']],
  ['KGZ', 'AS', 'Kyrgyzstan', ['wPqIACQ@EEk@DC@@@n@P@@N@PA?CI?AAE?ICREEE']],
  ['TKM', 'AS', 'Turkmenistan', ['cLmIKCKFC?G?MK}@d@?D@A^PFC@Eb@KRD?MHGAGM?FGFD']],
  ['IRN', 'AS', 'Iran', ['cKoFHSLKEGDGDIDQEAKFA?IEIHMJYCSEc@JADBH@JIPFFCBORJB@H^EFKVBNGJS']],
  ['SYR', 'AS', 'Syria', ['}GeG?CACCCBCAGCGc@AGABDDNPFNH']],
  ['ARM', 'AS', 'Armenia', ['sJuH@?JG@ADE@AKAA@IJ']],
  ['SWE', 'EU', 'Sweden', ['wAuMII@YCEG?Y_@YC?CE?IBKBCNL@FHZLDJMHNHDTVD']],
  ['BLR', 'EU', 'Belarus', ['aFaMG@KB?DOJJ@CFD?BDr@AB??C?K?CG?OI?ACA']],
  ['UKR', 'EU', 'Ukraine', ['}F_LC?KAKLe@F@JJFR@DFJATCHHD?BAA?KIHINA@?@?V@B??ADAAAAAA?IMBEC?s@@CE']],
  ['POL', 'EU', 'Poland', ['{DoL?B?J?BCDHL@?FCR?@?@CVEBABEBO[GQ@I@M?C?']],
  ['AUT', 'EU', 'Austria', ['gC_K?@B@@D@?H@F?HAJ?BAB?@A@AC?W?AGACEBQAC@']],
  ['HUN', 'EU', 'Hungary', ['oDcKE@?@D@FJD?D?D@@@JEB?@AAECA?AC@a@C']],
  ['MDA', 'EU', 'Moldova', ['sEaKA?O@IHJH@?@CFO']],
  ['ROU', 'EU', 'Romania', ['aFkJC@E?FJj@?@C@ALIBCE?GKEAC?WAA?C@GN']],
  ['LTU', 'EU', 'Lithuania', ['sE{L?@NHF?@AB??AJE@Ec@?']],
  ['LVA', 'EU', 'Latvia', ['yEkMC@?BCBHBB@FCb@?CKSBAEQ@']],
  ['EST', 'EU', 'Estonia', ['_F{M@LB@D?PAFK']],
  ['DEU', 'EU', 'Germany', ['oBmLCNCDB?PDEFC@@B@FV?B?FA@@D??ECEHABA?C@AAC@GECAIMC@GK?GFKC']],
  ['BGR', 'EU', 'Bulgaria', ['uDaJABk@?BLDAHB?BP?D??EBA?ACEBE']],
  ['GRC', 'EU', 'Greece', ['wDiIE?Q??CC@BDXBINHFCDJAJUEG?AEAGA']],
  ['TUR', 'AS', 'Turkey', ['eJiHB@JCB@F@b@@BF?GJ?PDd@EJUWMa@Ee@FYCG?GBA@EDA@D@EP', 'oEmIICE@EFRD@CCE']],
  ['ALB', 'EU', 'Albania', ['gDeI?@DFFSCCA?A@A??B?D']],
  ['HRV', 'EU', 'Croatia', ['cCsJC?KDAAABC@BBBAT@OLE@?@d@WK?CE']],
  ['CHE', 'EU', 'Switzerland', ['kA{JA@A@C?@BVDBA@CBAIEA?E?AA']],
  ['LUX', 'EU', 'Luxembourg', ['o@qKA@?B@?@??C']],
  ['BEL', 'EU', 'Belgium', ['q@uK@B@@?BFCPIE?Q@']],
  ['NLD', 'EU', 'Netherlands', ['w@kL@HDBAFDAPAKM']],
  ['PRT', 'EU', 'Portugal', ['fAoIEAMDFL?TJ@AKDC']],
  ['ESP', 'EU', 'Spain', ['z@gH?UGMLED@BGKEo@@g@FFHH@FLABPNXD']],
  ['IRL', 'EU', 'Ireland', ['p@mLBJXBEGBIQI?H']],
  ['NCL', 'OC', 'New Caledonia', ['mh@fDIHD?PQ']],
  ['SLB', 'OC', 'Solomon Is.', ['}f@~@A@?@DCDA@A?AC@']],
  ['NZL', 'OC', 'New Zealand', ['mi@zIWWKDJNABJBPRTG', 'gk@~HFHH?CEJGGONWKDMPS@']],
  ['AUS', 'OC', 'Australia', ['q^`GRL\\?NFVEEORq@CB@GEDDMAOWM_@GQYEB@CQQICSHGSOCDEC?WFICCBJTe@TGIIm@K\\CAEDI^QJGLG@OTETB\\Vl@\\JHGJDTEHMJEAGJDGQLNLSVG', '}c@dIC@@PN@HU']],
  ['LKA', 'AS', 'Sri Lanka', ['mS{@?FJBBQCK']],
  ['CHN', 'AS', 'China', ['aSqI?ECADMSCEMO@CKE?EEC?ADQDERa@FGJc@?a@Hk@IIGBECCM@_@OQ?LIP@CKCEIBUSBEYESDMVM@KL_@ENXN@@N?BDCl@VXFIKBC`@PQJGCMDXNUXDFEF@JV\\TLh@H@HB?@IL?TMRBB@B@?FB??A?ANAAGDGH?IODQD?FA@GJ@NHD@BAL?DD?ED?F?j@SB@HEHKE?@MHIJC@EDC@A@CDC@GAAo@Q', 'kZqCDGOE']],
  ['TWN', 'AS', 'Taiwan', ['m]cEFRDKKM']],
  ['ITA', 'EU', 'Italy', ['sAwJC@K?I@?BABL?AJo@\\LAAJFFBO`@QFMHAJBDO?AC@WE', 'uBqHE?BLRG', 'eAgIGB?HF@BO']],
  ['DNK', 'EU', 'Denmark', ['oAwLJ?@MQG@DEB', 'aB_M@HFC']],
  ['GBR', 'EU', 'United Kingdom', ['VkLNQBBDKIOO?FHOAFLG?SVI@@JFBl@DMKLCGA@I', 'p@mLHA?IMD']],
  ['ISL', 'EU', 'Iceland', ['rBsO@DIBh@L^CGCPCMCN?OGMD']],
  ['AZE', 'AS', 'Azerbaijan', ['sJmIA?GBECOJF?BNHIHD?EHK@AAAIB@E']],
  ['GEO', 'AS', 'Georgia', ['_I{Im@JE@@?ADHC@@J@FCF??I']],
  ['PHL', 'AS', 'Philippines', ['q]qCB^QB?HFGPAAEFGEW', 's^cA?H@FBGBBAHHEDKJBKKOA?E', 'k^aBAHDA@FBQ', 's]oAKIFP', 's\\iAHFQWAD', 'o]{AG?FF']],
  ['MYS', 'AS', 'Malaysia', ['o\\a@P?HTD@XBDIK@?GMAIKG@AIMKOJ', '_Xs@IDGCIJEVDBNK']],
  ['BRN', 'AS', 'Brunei', ['{[k@@HFA']],
  ['SVN', 'EU', 'Slovenia', ['mBsJG?IAA?A@D@BDJ?A?@C']],
  ['FIN', 'EU', 'Finland', ['cFgP?DKBFDIHDDGDBDKDZPh@DJGAS_@MJGBOJCHCCA[BKGU?']],
  ['SVK', 'EU', 'Slovakia', ['sDgK@@@@@@`@BBA?C?AKEA?A?S?']],
  ['CZE', 'EU', 'Czechia', ['wBwKC@WDAB@?JD?@BAP@DCBADGQE']],
  ['ERI', 'AF', 'Eritrea', ['cHsB@ACQMGEN]X@@B?@ANMNCBD']],
  ['JPN', 'AS', 'Japan', ['ob@yHL^VDJFDG^BGDDLF?AEFGWQY?GMEBOKEWGA', 'cc@_JECAHPHLEBHF?@GMGCO', 'a`@kGMEEBLF']],
  ['PRY', 'SA', 'Paraguay', ['pM`DCB@HQ@ALI?@H@B?DLFNCEMVINMCICI[?']],
  ['YEM', 'AS', 'Yemen', ['_LwCELAB`@Tb@JFEBWEI[BOK']],
  ['SAU', 'AS', 'Saudi Arabia', ['wGiFSECCFGOCAAI@a@TM@G?GBQ\\E??BCHWBAACDDNVFVBNJZCDHZg@DS\\a@']],
  ['ATA', 'AN', 'Antarctica', ['_l@dT?h@~xA??i@GCc@@c@C_BHwBArAIEM^Go@@a@GVGl@ATG@Gw@Bi@G@GIAwFKMF{ABECREHK{@Fq@AEE}@HICi@B}@IHUGK@G_@Qo@MABb@FDDED\\L_@TGVlAVt@?[H`@B?DUF{BPKDcAKw@@qBMHGn@@CKmCUMEDEGCi@OUBEEs@D_AMWDUEkBBg@EMIg@H}B_@w@PSCg@BEHNFIBFFMB_@S_@Ag@Q_@?IGMFo@@_@AWM[Jy@Gq@H[E{AAAGSL_A?YJk@?y@NmAHNNXDRLINQBh@BNLmAT', 'dKnRe@BEJx@F\\A', 'nQxPO?AMKCORBD\\@RC', 'pO`Su@ADF', '|g@rRS?OFN@', 'pX~Pk@?CB', 'r]lQ]AJB']],
  ['CYN', 'AS', 'N. Cyprus', ['eGyGMCBD']],
  ['CYP', 'AS', 'Cyprus', ['eGyGI@FB']],
  ['MAR', 'AF', 'Morocco', ['PyGGVz@Z?F?DT?Xj@P?Se@g@]@IGOMEGM']],
  ['EGY', 'AF', 'Egypt', ['eHoD|@?^??]Am@]DOEGBQACJDNLO[l@@F']],
  ['LBY', 'AF', 'Libya', ['gEoD?NH??B^O^OFDB@DCJCBCHCFKC[@ECAKU]FCDYHMSc@H@l@']],
  ['ETH', 'AF', 'Ethiopia', ['}J_ATVTDB@B?XBLGBEBABGLIEEAA?EQ_@AGG@CEOBOLA@@B@FE?A?@BIHYH']],
  ['DJI', 'AF', 'Djibouti', ['qIcBC?AAAHBB@?D?AG']],
  ['SOL', 'AF', 'Somaliland', ['gK{ABTDDD?XIHIACCCEF']],
  ['UGA', 'AF', 'Uganda', ['oGFP?F?@@D@@A?EMUBICAQ?CCCDCJFN']],
  ['RWA', 'AF', 'Rwanda', ['sFHAB@DBA@DDA?CAEAAA@']],
  ['BIH', 'EU', 'Bosnia and Herz.', ['sCuIDANMUAC@CH@?@?@@']],
  ['MKD', 'EU', 'North Macedonia', ['sDqIC@?D@?F@D@BA?EA?CCA?C?']],
  ['SRB', 'EU', 'Serbia', ['uCoJEAE?CBMHA@@@CDBD?@B?B?FE@@?ADA@AA?BICCBA']],
  ['MNE', 'EU', 'Montenegro', ['_DsI@?BBDC?AACAAA?A@E@?@']],
  ['KOS', 'EU', 'Kosovo', ['cDmI?C@?@AAAAAGD@?BB']],
  ['TTO', 'NA', 'Trinidad and Tobago', ['lNuAE??DF?']],
  ['SDS', 'AF', 'S. Sudan', ['uF[DENADE?APQBCBAMOGFQ?GEIBKSIT?D@@DDMHCFDDBBBBP?']],
];
