/**
 * Words that make a shot unfit for the mascot (PLAN.md#12.20, `mascot-impersonation`): a
 * profession, a role in a story, a title of a real person, or someone speaking. The one place of
 * the list (EN + PL); matched against the shot's intent, the mascot's action and the narration in
 * the shot. An entry ending in `*` matches every word starting with it (Polish inflection:
 * `lekarz*` = lekarz, lekarza, lekarzem, lekarze…); others match the whole word only.
 */

/** Professions and roles whose identity matters to the story. */
export const PERSON_ROLE_WORDS: readonly string[] = [
  // EN
  'doctor*',
  'physician*',
  'surgeon*',
  'nurse*',
  'dentist*',
  'patient',
  'patients',
  'scientist*',
  'researcher*',
  'professor*',
  'physicist*',
  'chemist',
  'chemists',
  'biologist*',
  'engineer',
  'engineers',
  'inventor',
  'inventors',
  'teacher*',
  'historian*',
  'lawyer*',
  'attorney*',
  'judge',
  'judges',
  'soldier*',
  'officer*',
  'police*',
  'policeman',
  'policemen',
  'detective*',
  'firefighter*',
  'pilot',
  'pilots',
  'astronaut*',
  'witness',
  'witnesses',
  'criminal*',
  'murderer*',
  'killer*',
  'thief',
  'thieves',
  'victim*',
  'hostage*',
  'ceo',
  'ceos',
  'founder*',
  'president*',
  'minister*',
  'senator*',
  'chancellor*',
  'mayor*',
  'king',
  'kings',
  'queen*',
  'emperor*',
  'pope',
  'priest*',
  // PL
  'lekarz*',
  'lekarka',
  'lekarki',
  'doktor*',
  'chirurg*',
  'pielęgniar*',
  'dentyst*',
  'pacjent*',
  'naukowiec',
  'naukowc*',
  'badacz*',
  'profesor*',
  'fizyk',
  'fizycy',
  'chemik*',
  'biolog',
  'biolodzy',
  'inżynier',
  'inżyniera',
  'inżynierem',
  'inżynierowie',
  'inżynierów',
  'inżynierka',
  'wynalazc*',
  'nauczyciel*',
  'historyk*',
  'prawnik*',
  'adwokat*',
  'sędzi*',
  'żołnierz*',
  'generał*',
  'oficer*',
  'policjan*',
  'detektyw*',
  'strażak*',
  'pilot*',
  'astronaut*',
  'świadek',
  'świadka',
  'świadkiem',
  'świadkowie',
  'świadków',
  'przestępca',
  'przestępcy',
  'przestępcą',
  'przestępców',
  'morderc*',
  'złodziej*',
  'ofiar*',
  'zakładni*',
  'prezes*',
  'założyciel*',
  'prezydent*',
  'premier',
  'ministr*',
  'minister',
  'senator*',
  'burmistrz*',
  'król',
  'króla',
  'królem',
  'królowie',
  'królów',
  'królow*',
  'cesarz*',
  'papież*',
  'ksiądz',
  'księdz*',
];

/** Verbs of reported speech: someone is quoted (a speaker the mascot must not play). */
export const SPEECH_WORDS: readonly string[] = [
  // EN
  'said',
  'told',
  'replied',
  'declared',
  // PL
  'powiedział*',
  'stwierdził*',
  'oświadczył*',
  'odpowiedział*',
];

/** Quotation marks around spoken words (straight, curly, Polish low and guillemets). */
export const QUOTE_CHARACTERS: readonly string[] = ['"', '“', '”', '„', '«', '»'];

/** Honorifics before a name (`Dr Kowalski`, `Mr Jobs`, `pan Nowak`). */
export const HONORIFICS: readonly string[] = [
  'mr',
  'mrs',
  'ms',
  'miss',
  'dr',
  'sir',
  'lady',
  'lord',
  'pan',
  'pani',
  'prof',
];

/**
 * First words of capitalised pairs that are not a person's name (sentence openers, places,
 * events): `The Nokia`, `New York`, `World War`; `*` as in PERSON_ROLE_WORDS.
 */
export const NOT_A_FIRST_NAME: readonly string[] = [
  // EN function words and openers
  'a',
  'an',
  'the',
  'this',
  'that',
  'these',
  'those',
  'in',
  'on',
  'at',
  'by',
  'for',
  'from',
  'to',
  'of',
  'and',
  'but',
  'or',
  'so',
  'then',
  'when',
  'while',
  'why',
  'how',
  'what',
  'who',
  'it',
  'its',
  'we',
  'you',
  'they',
  'he',
  'she',
  'i',
  'his',
  'her',
  'their',
  'our',
  'your',
  'my',
  'every',
  'each',
  'all',
  'some',
  'no',
  'yes',
  'now',
  'today',
  'here',
  'there',
  'after',
  'before',
  'since',
  'until',
  'if',
  'as',
  'with',
  'without',
  // EN places and events
  'new',
  'los',
  'las',
  'san',
  'santa',
  'saint',
  'st',
  'hong',
  'north',
  'south',
  'east',
  'west',
  'united',
  'great',
  'silicon',
  'world',
  'cold',
  'first',
  'second',
  'middle',
  'old',
  // PL function words and openers
  'w',
  'we',
  'na',
  'z',
  'ze',
  'do',
  'od',
  'po',
  'przez',
  'dla',
  'i',
  'a',
  'ale',
  'to',
  'ten',
  'ta',
  'te',
  'tak',
  'nie',
  'kiedy',
  'gdy',
  'dlaczego',
  'jak',
  'co',
  'kto',
  'czy',
  'potem',
  'teraz',
  'dziś',
  'dzisiaj',
  'tu',
  'tam',
  'jego',
  'jej',
  'ich',
  'nasz',
  'wasz',
  'mój',
  'każdy',
  'wszyscy',
  // PL places and events (inflected: Nowym Jorku, Stanach Zjednoczonych, Wielkiej Brytanii)
  'now*',
  'stany',
  'stanach',
  'stanów',
  'stanami',
  'wielk*',
  'zimn*',
  'ii',
];

export type WordList = readonly string[];

/** True when the lower-case `token` matches an entry of `list` (see the file comment). */
export function matchesWordList(token: string, list: WordList): string | undefined {
  for (const entry of list) {
    if (entry.endsWith('*')) {
      if (token.startsWith(entry.slice(0, -1))) return entry;
    } else if (token === entry) {
      return entry;
    }
  }
  return undefined;
}
